# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flashreduce.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'flashreduce.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x66lashreduce.proto\x12\x11\x66lashreduce_proto\"\xdf\x01\n\x12RdmaSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\r\x12\x0c\n\x04rank\x18\x02 \x01(\r\x12\x13\n\x0bnum_workers\x18\x03 \x01(\r\x12\x0c\n\x04root\x18\x04 \x01(\r\x12\x0b\n\x03mac\x18\x05 \x01(\x04\x12\x0c\n\x04ipv4\x18\x06 \x01(\r\x12\x0c\n\x04rkey\x18\x07 \x01(\r\x12\r\n\x05raddr\x18\x08 \x01(\x04\x12\x0b\n\x03qpn\x18\t \x01(\r\x12\x0b\n\x03psn\x18\n \x01(\r\x12\x12\n\ngid_subnet\x18\x0b \x01(\x04\x12\x11\n\tgid_iface\x18\x0c \x01(\x04\x12\x0b\n\x03lid\x18\r \x01(\r\"\x80\x01\n\x13RdmaSessionResponse\x12\x0c\n\x04rkey\x18\x02 \x01(\r\x12\r\n\x05raddr\x18\x03 \x01(\x04\x12\x0b\n\x03qpn\x18\x04 \x01(\r\x12\x0b\n\x03psn\x18\x05 \x01(\r\x12\x12\n\ngid_subnet\x18\r \x01(\x04\x12\x11\n\tgid_iface\x18\x0e \x01(\x04\x12\x0b\n\x03lid\x18\x0f \x01(\r\"%\n\x0e\x42\x61rrierRequest\x12\x13\n\x0bnum_workers\x18\x01 \x01(\r\"\x11\n\x0f\x42\x61rrierResponse\"R\n\x10\x42roadcastRequest\x12\r\n\x05value\x18\x01 \x01(\x04\x12\x0c\n\x04rank\x18\x02 \x01(\r\x12\x13\n\x0bnum_workers\x18\x03 \x01(\r\x12\x0c\n\x04root\x18\x04 \x01(\r\"\"\n\x11\x42roadcastResponse\x12\r\n\x05value\x18\x01 \x01(\x04\x32i\n\x07Session\x12^\n\x0bRdmaSession\x12%.flashreduce_proto.RdmaSessionRequest\x1a&.flashreduce_proto.RdmaSessionResponse\"\x00\x32\xb4\x01\n\x04Sync\x12R\n\x07\x42\x61rrier\x12!.flashreduce_proto.BarrierRequest\x1a\".flashreduce_proto.BarrierResponse\"\x00\x12X\n\tBroadcast\x12#.flashreduce_proto.BroadcastRequest\x1a$.flashreduce_proto.BroadcastResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flashreduce_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RDMASESSIONREQUEST']._serialized_start=41
  _globals['_RDMASESSIONREQUEST']._serialized_end=264
  _globals['_RDMASESSIONRESPONSE']._serialized_start=267
  _globals['_RDMASESSIONRESPONSE']._serialized_end=395
  _globals['_BARRIERREQUEST']._serialized_start=397
  _globals['_BARRIERREQUEST']._serialized_end=434
  _globals['_BARRIERRESPONSE']._serialized_start=436
  _globals['_BARRIERRESPONSE']._serialized_end=453
  _globals['_BROADCASTREQUEST']._serialized_start=455
  _globals['_BROADCASTREQUEST']._serialized_end=537
  _globals['_BROADCASTRESPONSE']._serialized_start=539
  _globals['_BROADCASTRESPONSE']._serialized_end=573
  _globals['_SESSION']._serialized_start=575
  _globals['_SESSION']._serialized_end=680
  _globals['_SYNC']._serialized_start=683
  _globals['_SYNC']._serialized_end=863
# @@protoc_insertion_point(module_scope)
