# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flashreduce.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'flashreduce.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x66lashreduce.proto\x12\x11\x66lashreduce_proto\"\xda\x01\n\x12RdmaSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\r\x12\x0c\n\x04rank\x18\x02 \x01(\r\x12\x13\n\x0bnum_workers\x18\x03 \x01(\r\x12\x0b\n\x03mac\x18\x04 \x01(\x04\x12\x0c\n\x04ipv4\x18\x05 \x01(\r\x12\x0c\n\x04rkey\x18\x06 \x01(\r\x12\x32\n\x0bpacket_size\x18\x07 \x01(\x0e\x32\x1d.flashreduce_proto.PacketSize\x12\x14\n\x0cmessage_size\x18\x08 \x01(\r\x12\x0c\n\x04qpns\x18\t \x03(\r\x12\x0c\n\x04psns\x18\n \x03(\r\"n\n\x13RdmaSessionResponse\x12\x12\n\nsession_id\x18\x01 \x01(\x04\x12\x0b\n\x03mac\x18\x02 \x01(\x04\x12\x0c\n\x04ipv4\x18\x03 \x01(\r\x12\x0c\n\x04rkey\x18\x04 \x01(\r\x12\x0c\n\x04qpns\x18\x05 \x03(\r\x12\x0c\n\x04psns\x18\x06 \x03(\r\"%\n\x0e\x42\x61rrierRequest\x12\x13\n\x0bnum_workers\x18\x01 \x01(\r\"\x11\n\x0f\x42\x61rrierResponse\"R\n\x10\x42roadcastRequest\x12\r\n\x05value\x18\x01 \x01(\x04\x12\x0c\n\x04rank\x18\x02 \x01(\r\x12\x13\n\x0bnum_workers\x18\x03 \x01(\r\x12\x0c\n\x04root\x18\x04 \x01(\r\"\"\n\x11\x42roadcastResponse\x12\r\n\x05value\x18\x01 \x01(\x04*\'\n\nPacketSize\x12\x0b\n\x07MTU_256\x10\x00\x12\x0c\n\x08MTU_1024\x10\x01\x32i\n\x07Session\x12^\n\x0bRdmaSession\x12%.flashreduce_proto.RdmaSessionRequest\x1a&.flashreduce_proto.RdmaSessionResponse\"\x00\x32\xb4\x01\n\x04Sync\x12R\n\x07\x42\x61rrier\x12!.flashreduce_proto.BarrierRequest\x1a\".flashreduce_proto.BarrierResponse\"\x00\x12X\n\tBroadcast\x12#.flashreduce_proto.BroadcastRequest\x1a$.flashreduce_proto.BroadcastResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flashreduce_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PACKETSIZE']._serialized_start=551
  _globals['_PACKETSIZE']._serialized_end=590
  _globals['_RDMASESSIONREQUEST']._serialized_start=41
  _globals['_RDMASESSIONREQUEST']._serialized_end=259
  _globals['_RDMASESSIONRESPONSE']._serialized_start=261
  _globals['_RDMASESSIONRESPONSE']._serialized_end=371
  _globals['_BARRIERREQUEST']._serialized_start=373
  _globals['_BARRIERREQUEST']._serialized_end=410
  _globals['_BARRIERRESPONSE']._serialized_start=412
  _globals['_BARRIERRESPONSE']._serialized_end=429
  _globals['_BROADCASTREQUEST']._serialized_start=431
  _globals['_BROADCASTREQUEST']._serialized_end=513
  _globals['_BROADCASTRESPONSE']._serialized_start=515
  _globals['_BROADCASTRESPONSE']._serialized_end=549
  _globals['_SESSION']._serialized_start=592
  _globals['_SESSION']._serialized_end=697
  _globals['_SYNC']._serialized_start=700
  _globals['_SYNC']._serialized_end=880
# @@protoc_insertion_point(module_scope)
