// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: flashreduce.proto
// Protobuf C++ Version: 5.29.0

#ifndef flashreduce_2eproto_2epb_2eh
#define flashreduce_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_flashreduce_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_flashreduce_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_flashreduce_2eproto;
namespace flashreduce_proto {
class BarrierRequest;
struct BarrierRequestDefaultTypeInternal;
extern BarrierRequestDefaultTypeInternal _BarrierRequest_default_instance_;
class BarrierResponse;
struct BarrierResponseDefaultTypeInternal;
extern BarrierResponseDefaultTypeInternal _BarrierResponse_default_instance_;
class BroadcastRequest;
struct BroadcastRequestDefaultTypeInternal;
extern BroadcastRequestDefaultTypeInternal _BroadcastRequest_default_instance_;
class BroadcastResponse;
struct BroadcastResponseDefaultTypeInternal;
extern BroadcastResponseDefaultTypeInternal _BroadcastResponse_default_instance_;
class RdmaSessionRequest;
struct RdmaSessionRequestDefaultTypeInternal;
extern RdmaSessionRequestDefaultTypeInternal _RdmaSessionRequest_default_instance_;
class RdmaSessionResponse;
struct RdmaSessionResponseDefaultTypeInternal;
extern RdmaSessionResponseDefaultTypeInternal _RdmaSessionResponse_default_instance_;
}  // namespace flashreduce_proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace flashreduce_proto {
enum PacketSize : int {
  MTU_256 = 0,
  MTU_1024 = 1,
  PacketSize_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  PacketSize_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool PacketSize_IsValid(int value);
extern const uint32_t PacketSize_internal_data_[];
constexpr PacketSize PacketSize_MIN = static_cast<PacketSize>(0);
constexpr PacketSize PacketSize_MAX = static_cast<PacketSize>(1);
constexpr int PacketSize_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor*
PacketSize_descriptor();
template <typename T>
const std::string& PacketSize_Name(T value) {
  static_assert(std::is_same<T, PacketSize>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to PacketSize_Name().");
  return PacketSize_Name(static_cast<PacketSize>(value));
}
template <>
inline const std::string& PacketSize_Name(PacketSize value) {
  return ::google::protobuf::internal::NameOfDenseEnum<PacketSize_descriptor,
                                                 0, 1>(
      static_cast<int>(value));
}
inline bool PacketSize_Parse(absl::string_view name, PacketSize* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PacketSize>(
      PacketSize_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class RdmaSessionResponse final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:flashreduce_proto.RdmaSessionResponse) */ {
 public:
  inline RdmaSessionResponse() : RdmaSessionResponse(nullptr) {}
  ~RdmaSessionResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RdmaSessionResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RdmaSessionResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RdmaSessionResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline RdmaSessionResponse(const RdmaSessionResponse& from) : RdmaSessionResponse(nullptr, from) {}
  inline RdmaSessionResponse(RdmaSessionResponse&& from) noexcept
      : RdmaSessionResponse(nullptr, std::move(from)) {}
  inline RdmaSessionResponse& operator=(const RdmaSessionResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline RdmaSessionResponse& operator=(RdmaSessionResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RdmaSessionResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const RdmaSessionResponse* internal_default_instance() {
    return reinterpret_cast<const RdmaSessionResponse*>(
        &_RdmaSessionResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(RdmaSessionResponse& a, RdmaSessionResponse& b) { a.Swap(&b); }
  inline void Swap(RdmaSessionResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RdmaSessionResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RdmaSessionResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RdmaSessionResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RdmaSessionResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RdmaSessionResponse& from) { RdmaSessionResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RdmaSessionResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "flashreduce_proto.RdmaSessionResponse"; }

 protected:
  explicit RdmaSessionResponse(::google::protobuf::Arena* arena);
  RdmaSessionResponse(::google::protobuf::Arena* arena, const RdmaSessionResponse& from);
  RdmaSessionResponse(::google::protobuf::Arena* arena, RdmaSessionResponse&& from) noexcept
      : RdmaSessionResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kQpnsFieldNumber = 5,
    kPsnsFieldNumber = 6,
    kSessionIdFieldNumber = 1,
    kMacFieldNumber = 2,
    kIpv4FieldNumber = 3,
    kRkeyFieldNumber = 4,
  };
  // repeated uint32 qpns = 5;
  int qpns_size() const;
  private:
  int _internal_qpns_size() const;

  public:
  void clear_qpns() ;
  ::uint32_t qpns(int index) const;
  void set_qpns(int index, ::uint32_t value);
  void add_qpns(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& qpns() const;
  ::google::protobuf::RepeatedField<::uint32_t>* mutable_qpns();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_qpns() const;
  ::google::protobuf::RepeatedField<::uint32_t>* _internal_mutable_qpns();

  public:
  // repeated uint32 psns = 6;
  int psns_size() const;
  private:
  int _internal_psns_size() const;

  public:
  void clear_psns() ;
  ::uint32_t psns(int index) const;
  void set_psns(int index, ::uint32_t value);
  void add_psns(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& psns() const;
  ::google::protobuf::RepeatedField<::uint32_t>* mutable_psns();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_psns() const;
  ::google::protobuf::RepeatedField<::uint32_t>* _internal_mutable_psns();

  public:
  // uint64 session_id = 1;
  void clear_session_id() ;
  ::uint64_t session_id() const;
  void set_session_id(::uint64_t value);

  private:
  ::uint64_t _internal_session_id() const;
  void _internal_set_session_id(::uint64_t value);

  public:
  // uint64 mac = 2;
  void clear_mac() ;
  ::uint64_t mac() const;
  void set_mac(::uint64_t value);

  private:
  ::uint64_t _internal_mac() const;
  void _internal_set_mac(::uint64_t value);

  public:
  // uint32 ipv4 = 3;
  void clear_ipv4() ;
  ::uint32_t ipv4() const;
  void set_ipv4(::uint32_t value);

  private:
  ::uint32_t _internal_ipv4() const;
  void _internal_set_ipv4(::uint32_t value);

  public:
  // uint32 rkey = 4;
  void clear_rkey() ;
  ::uint32_t rkey() const;
  void set_rkey(::uint32_t value);

  private:
  ::uint32_t _internal_rkey() const;
  void _internal_set_rkey(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:flashreduce_proto.RdmaSessionResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const RdmaSessionResponse& from_msg);
    ::google::protobuf::RepeatedField<::uint32_t> qpns_;
    ::google::protobuf::internal::CachedSize _qpns_cached_byte_size_;
    ::google::protobuf::RepeatedField<::uint32_t> psns_;
    ::google::protobuf::internal::CachedSize _psns_cached_byte_size_;
    ::uint64_t session_id_;
    ::uint64_t mac_;
    ::uint32_t ipv4_;
    ::uint32_t rkey_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_flashreduce_2eproto;
};
// -------------------------------------------------------------------

class RdmaSessionRequest final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:flashreduce_proto.RdmaSessionRequest) */ {
 public:
  inline RdmaSessionRequest() : RdmaSessionRequest(nullptr) {}
  ~RdmaSessionRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RdmaSessionRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RdmaSessionRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RdmaSessionRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline RdmaSessionRequest(const RdmaSessionRequest& from) : RdmaSessionRequest(nullptr, from) {}
  inline RdmaSessionRequest(RdmaSessionRequest&& from) noexcept
      : RdmaSessionRequest(nullptr, std::move(from)) {}
  inline RdmaSessionRequest& operator=(const RdmaSessionRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline RdmaSessionRequest& operator=(RdmaSessionRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RdmaSessionRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const RdmaSessionRequest* internal_default_instance() {
    return reinterpret_cast<const RdmaSessionRequest*>(
        &_RdmaSessionRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RdmaSessionRequest& a, RdmaSessionRequest& b) { a.Swap(&b); }
  inline void Swap(RdmaSessionRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RdmaSessionRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RdmaSessionRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RdmaSessionRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RdmaSessionRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RdmaSessionRequest& from) { RdmaSessionRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RdmaSessionRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "flashreduce_proto.RdmaSessionRequest"; }

 protected:
  explicit RdmaSessionRequest(::google::protobuf::Arena* arena);
  RdmaSessionRequest(::google::protobuf::Arena* arena, const RdmaSessionRequest& from);
  RdmaSessionRequest(::google::protobuf::Arena* arena, RdmaSessionRequest&& from) noexcept
      : RdmaSessionRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kQpnsFieldNumber = 9,
    kPsnsFieldNumber = 10,
    kSessionIdFieldNumber = 1,
    kRankFieldNumber = 2,
    kMacFieldNumber = 4,
    kNumWorkersFieldNumber = 3,
    kIpv4FieldNumber = 5,
    kRkeyFieldNumber = 6,
    kPacketSizeFieldNumber = 7,
    kMessageSizeFieldNumber = 8,
  };
  // repeated uint32 qpns = 9;
  int qpns_size() const;
  private:
  int _internal_qpns_size() const;

  public:
  void clear_qpns() ;
  ::uint32_t qpns(int index) const;
  void set_qpns(int index, ::uint32_t value);
  void add_qpns(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& qpns() const;
  ::google::protobuf::RepeatedField<::uint32_t>* mutable_qpns();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_qpns() const;
  ::google::protobuf::RepeatedField<::uint32_t>* _internal_mutable_qpns();

  public:
  // repeated uint32 psns = 10;
  int psns_size() const;
  private:
  int _internal_psns_size() const;

  public:
  void clear_psns() ;
  ::uint32_t psns(int index) const;
  void set_psns(int index, ::uint32_t value);
  void add_psns(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& psns() const;
  ::google::protobuf::RepeatedField<::uint32_t>* mutable_psns();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_psns() const;
  ::google::protobuf::RepeatedField<::uint32_t>* _internal_mutable_psns();

  public:
  // uint32 session_id = 1;
  void clear_session_id() ;
  ::uint32_t session_id() const;
  void set_session_id(::uint32_t value);

  private:
  ::uint32_t _internal_session_id() const;
  void _internal_set_session_id(::uint32_t value);

  public:
  // uint32 rank = 2;
  void clear_rank() ;
  ::uint32_t rank() const;
  void set_rank(::uint32_t value);

  private:
  ::uint32_t _internal_rank() const;
  void _internal_set_rank(::uint32_t value);

  public:
  // uint64 mac = 4;
  void clear_mac() ;
  ::uint64_t mac() const;
  void set_mac(::uint64_t value);

  private:
  ::uint64_t _internal_mac() const;
  void _internal_set_mac(::uint64_t value);

  public:
  // uint32 num_workers = 3;
  void clear_num_workers() ;
  ::uint32_t num_workers() const;
  void set_num_workers(::uint32_t value);

  private:
  ::uint32_t _internal_num_workers() const;
  void _internal_set_num_workers(::uint32_t value);

  public:
  // uint32 ipv4 = 5;
  void clear_ipv4() ;
  ::uint32_t ipv4() const;
  void set_ipv4(::uint32_t value);

  private:
  ::uint32_t _internal_ipv4() const;
  void _internal_set_ipv4(::uint32_t value);

  public:
  // uint32 rkey = 6;
  void clear_rkey() ;
  ::uint32_t rkey() const;
  void set_rkey(::uint32_t value);

  private:
  ::uint32_t _internal_rkey() const;
  void _internal_set_rkey(::uint32_t value);

  public:
  // .flashreduce_proto.PacketSize packet_size = 7;
  void clear_packet_size() ;
  ::flashreduce_proto::PacketSize packet_size() const;
  void set_packet_size(::flashreduce_proto::PacketSize value);

  private:
  ::flashreduce_proto::PacketSize _internal_packet_size() const;
  void _internal_set_packet_size(::flashreduce_proto::PacketSize value);

  public:
  // uint32 message_size = 8;
  void clear_message_size() ;
  ::uint32_t message_size() const;
  void set_message_size(::uint32_t value);

  private:
  ::uint32_t _internal_message_size() const;
  void _internal_set_message_size(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:flashreduce_proto.RdmaSessionRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 10, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const RdmaSessionRequest& from_msg);
    ::google::protobuf::RepeatedField<::uint32_t> qpns_;
    ::google::protobuf::internal::CachedSize _qpns_cached_byte_size_;
    ::google::protobuf::RepeatedField<::uint32_t> psns_;
    ::google::protobuf::internal::CachedSize _psns_cached_byte_size_;
    ::uint32_t session_id_;
    ::uint32_t rank_;
    ::uint64_t mac_;
    ::uint32_t num_workers_;
    ::uint32_t ipv4_;
    ::uint32_t rkey_;
    int packet_size_;
    ::uint32_t message_size_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_flashreduce_2eproto;
};
// -------------------------------------------------------------------

class BroadcastResponse final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:flashreduce_proto.BroadcastResponse) */ {
 public:
  inline BroadcastResponse() : BroadcastResponse(nullptr) {}
  ~BroadcastResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BroadcastResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BroadcastResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BroadcastResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline BroadcastResponse(const BroadcastResponse& from) : BroadcastResponse(nullptr, from) {}
  inline BroadcastResponse(BroadcastResponse&& from) noexcept
      : BroadcastResponse(nullptr, std::move(from)) {}
  inline BroadcastResponse& operator=(const BroadcastResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline BroadcastResponse& operator=(BroadcastResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BroadcastResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const BroadcastResponse* internal_default_instance() {
    return reinterpret_cast<const BroadcastResponse*>(
        &_BroadcastResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(BroadcastResponse& a, BroadcastResponse& b) { a.Swap(&b); }
  inline void Swap(BroadcastResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BroadcastResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BroadcastResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BroadcastResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BroadcastResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BroadcastResponse& from) { BroadcastResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BroadcastResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "flashreduce_proto.BroadcastResponse"; }

 protected:
  explicit BroadcastResponse(::google::protobuf::Arena* arena);
  BroadcastResponse(::google::protobuf::Arena* arena, const BroadcastResponse& from);
  BroadcastResponse(::google::protobuf::Arena* arena, BroadcastResponse&& from) noexcept
      : BroadcastResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kValueFieldNumber = 1,
  };
  // uint64 value = 1;
  void clear_value() ;
  ::uint64_t value() const;
  void set_value(::uint64_t value);

  private:
  ::uint64_t _internal_value() const;
  void _internal_set_value(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:flashreduce_proto.BroadcastResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const BroadcastResponse& from_msg);
    ::uint64_t value_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_flashreduce_2eproto;
};
// -------------------------------------------------------------------

class BroadcastRequest final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:flashreduce_proto.BroadcastRequest) */ {
 public:
  inline BroadcastRequest() : BroadcastRequest(nullptr) {}
  ~BroadcastRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BroadcastRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BroadcastRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BroadcastRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline BroadcastRequest(const BroadcastRequest& from) : BroadcastRequest(nullptr, from) {}
  inline BroadcastRequest(BroadcastRequest&& from) noexcept
      : BroadcastRequest(nullptr, std::move(from)) {}
  inline BroadcastRequest& operator=(const BroadcastRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline BroadcastRequest& operator=(BroadcastRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BroadcastRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const BroadcastRequest* internal_default_instance() {
    return reinterpret_cast<const BroadcastRequest*>(
        &_BroadcastRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(BroadcastRequest& a, BroadcastRequest& b) { a.Swap(&b); }
  inline void Swap(BroadcastRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BroadcastRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BroadcastRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BroadcastRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BroadcastRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BroadcastRequest& from) { BroadcastRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BroadcastRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "flashreduce_proto.BroadcastRequest"; }

 protected:
  explicit BroadcastRequest(::google::protobuf::Arena* arena);
  BroadcastRequest(::google::protobuf::Arena* arena, const BroadcastRequest& from);
  BroadcastRequest(::google::protobuf::Arena* arena, BroadcastRequest&& from) noexcept
      : BroadcastRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kValueFieldNumber = 1,
    kRankFieldNumber = 2,
    kNumWorkersFieldNumber = 3,
    kRootFieldNumber = 4,
  };
  // uint64 value = 1;
  void clear_value() ;
  ::uint64_t value() const;
  void set_value(::uint64_t value);

  private:
  ::uint64_t _internal_value() const;
  void _internal_set_value(::uint64_t value);

  public:
  // uint32 rank = 2;
  void clear_rank() ;
  ::uint32_t rank() const;
  void set_rank(::uint32_t value);

  private:
  ::uint32_t _internal_rank() const;
  void _internal_set_rank(::uint32_t value);

  public:
  // uint32 num_workers = 3;
  void clear_num_workers() ;
  ::uint32_t num_workers() const;
  void set_num_workers(::uint32_t value);

  private:
  ::uint32_t _internal_num_workers() const;
  void _internal_set_num_workers(::uint32_t value);

  public:
  // uint32 root = 4;
  void clear_root() ;
  ::uint32_t root() const;
  void set_root(::uint32_t value);

  private:
  ::uint32_t _internal_root() const;
  void _internal_set_root(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:flashreduce_proto.BroadcastRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const BroadcastRequest& from_msg);
    ::uint64_t value_;
    ::uint32_t rank_;
    ::uint32_t num_workers_;
    ::uint32_t root_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_flashreduce_2eproto;
};
// -------------------------------------------------------------------

class BarrierResponse final
    : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:flashreduce_proto.BarrierResponse) */ {
 public:
  inline BarrierResponse() : BarrierResponse(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BarrierResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BarrierResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BarrierResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline BarrierResponse(const BarrierResponse& from) : BarrierResponse(nullptr, from) {}
  inline BarrierResponse(BarrierResponse&& from) noexcept
      : BarrierResponse(nullptr, std::move(from)) {}
  inline BarrierResponse& operator=(const BarrierResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline BarrierResponse& operator=(BarrierResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BarrierResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const BarrierResponse* internal_default_instance() {
    return reinterpret_cast<const BarrierResponse*>(
        &_BarrierResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(BarrierResponse& a, BarrierResponse& b) { a.Swap(&b); }
  inline void Swap(BarrierResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BarrierResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BarrierResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<BarrierResponse>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const BarrierResponse& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const BarrierResponse& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "flashreduce_proto.BarrierResponse"; }

 protected:
  explicit BarrierResponse(::google::protobuf::Arena* arena);
  BarrierResponse(::google::protobuf::Arena* arena, const BarrierResponse& from);
  BarrierResponse(::google::protobuf::Arena* arena, BarrierResponse&& from) noexcept
      : BarrierResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:flashreduce_proto.BarrierResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const BarrierResponse& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_flashreduce_2eproto;
};
// -------------------------------------------------------------------

class BarrierRequest final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:flashreduce_proto.BarrierRequest) */ {
 public:
  inline BarrierRequest() : BarrierRequest(nullptr) {}
  ~BarrierRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BarrierRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BarrierRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BarrierRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline BarrierRequest(const BarrierRequest& from) : BarrierRequest(nullptr, from) {}
  inline BarrierRequest(BarrierRequest&& from) noexcept
      : BarrierRequest(nullptr, std::move(from)) {}
  inline BarrierRequest& operator=(const BarrierRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline BarrierRequest& operator=(BarrierRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BarrierRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const BarrierRequest* internal_default_instance() {
    return reinterpret_cast<const BarrierRequest*>(
        &_BarrierRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(BarrierRequest& a, BarrierRequest& b) { a.Swap(&b); }
  inline void Swap(BarrierRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BarrierRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BarrierRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BarrierRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BarrierRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BarrierRequest& from) { BarrierRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BarrierRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "flashreduce_proto.BarrierRequest"; }

 protected:
  explicit BarrierRequest(::google::protobuf::Arena* arena);
  BarrierRequest(::google::protobuf::Arena* arena, const BarrierRequest& from);
  BarrierRequest(::google::protobuf::Arena* arena, BarrierRequest&& from) noexcept
      : BarrierRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNumWorkersFieldNumber = 1,
  };
  // uint32 num_workers = 1;
  void clear_num_workers() ;
  ::uint32_t num_workers() const;
  void set_num_workers(::uint32_t value);

  private:
  ::uint32_t _internal_num_workers() const;
  void _internal_set_num_workers(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:flashreduce_proto.BarrierRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const BarrierRequest& from_msg);
    ::uint32_t num_workers_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_flashreduce_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RdmaSessionRequest

// uint32 session_id = 1;
inline void RdmaSessionRequest::clear_session_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_id_ = 0u;
}
inline ::uint32_t RdmaSessionRequest::session_id() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionRequest.session_id)
  return _internal_session_id();
}
inline void RdmaSessionRequest::set_session_id(::uint32_t value) {
  _internal_set_session_id(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionRequest.session_id)
}
inline ::uint32_t RdmaSessionRequest::_internal_session_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.session_id_;
}
inline void RdmaSessionRequest::_internal_set_session_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_id_ = value;
}

// uint32 rank = 2;
inline void RdmaSessionRequest::clear_rank() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rank_ = 0u;
}
inline ::uint32_t RdmaSessionRequest::rank() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionRequest.rank)
  return _internal_rank();
}
inline void RdmaSessionRequest::set_rank(::uint32_t value) {
  _internal_set_rank(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionRequest.rank)
}
inline ::uint32_t RdmaSessionRequest::_internal_rank() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rank_;
}
inline void RdmaSessionRequest::_internal_set_rank(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rank_ = value;
}

// uint32 num_workers = 3;
inline void RdmaSessionRequest::clear_num_workers() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_workers_ = 0u;
}
inline ::uint32_t RdmaSessionRequest::num_workers() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionRequest.num_workers)
  return _internal_num_workers();
}
inline void RdmaSessionRequest::set_num_workers(::uint32_t value) {
  _internal_set_num_workers(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionRequest.num_workers)
}
inline ::uint32_t RdmaSessionRequest::_internal_num_workers() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num_workers_;
}
inline void RdmaSessionRequest::_internal_set_num_workers(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_workers_ = value;
}

// uint64 mac = 4;
inline void RdmaSessionRequest::clear_mac() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mac_ = ::uint64_t{0u};
}
inline ::uint64_t RdmaSessionRequest::mac() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionRequest.mac)
  return _internal_mac();
}
inline void RdmaSessionRequest::set_mac(::uint64_t value) {
  _internal_set_mac(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionRequest.mac)
}
inline ::uint64_t RdmaSessionRequest::_internal_mac() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.mac_;
}
inline void RdmaSessionRequest::_internal_set_mac(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mac_ = value;
}

// uint32 ipv4 = 5;
inline void RdmaSessionRequest::clear_ipv4() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ipv4_ = 0u;
}
inline ::uint32_t RdmaSessionRequest::ipv4() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionRequest.ipv4)
  return _internal_ipv4();
}
inline void RdmaSessionRequest::set_ipv4(::uint32_t value) {
  _internal_set_ipv4(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionRequest.ipv4)
}
inline ::uint32_t RdmaSessionRequest::_internal_ipv4() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ipv4_;
}
inline void RdmaSessionRequest::_internal_set_ipv4(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ipv4_ = value;
}

// uint32 rkey = 6;
inline void RdmaSessionRequest::clear_rkey() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rkey_ = 0u;
}
inline ::uint32_t RdmaSessionRequest::rkey() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionRequest.rkey)
  return _internal_rkey();
}
inline void RdmaSessionRequest::set_rkey(::uint32_t value) {
  _internal_set_rkey(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionRequest.rkey)
}
inline ::uint32_t RdmaSessionRequest::_internal_rkey() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rkey_;
}
inline void RdmaSessionRequest::_internal_set_rkey(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rkey_ = value;
}

// .flashreduce_proto.PacketSize packet_size = 7;
inline void RdmaSessionRequest::clear_packet_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.packet_size_ = 0;
}
inline ::flashreduce_proto::PacketSize RdmaSessionRequest::packet_size() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionRequest.packet_size)
  return _internal_packet_size();
}
inline void RdmaSessionRequest::set_packet_size(::flashreduce_proto::PacketSize value) {
  _internal_set_packet_size(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionRequest.packet_size)
}
inline ::flashreduce_proto::PacketSize RdmaSessionRequest::_internal_packet_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::flashreduce_proto::PacketSize>(_impl_.packet_size_);
}
inline void RdmaSessionRequest::_internal_set_packet_size(::flashreduce_proto::PacketSize value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.packet_size_ = value;
}

// uint32 message_size = 8;
inline void RdmaSessionRequest::clear_message_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_size_ = 0u;
}
inline ::uint32_t RdmaSessionRequest::message_size() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionRequest.message_size)
  return _internal_message_size();
}
inline void RdmaSessionRequest::set_message_size(::uint32_t value) {
  _internal_set_message_size(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionRequest.message_size)
}
inline ::uint32_t RdmaSessionRequest::_internal_message_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_size_;
}
inline void RdmaSessionRequest::_internal_set_message_size(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_size_ = value;
}

// repeated uint32 qpns = 9;
inline int RdmaSessionRequest::_internal_qpns_size() const {
  return _internal_qpns().size();
}
inline int RdmaSessionRequest::qpns_size() const {
  return _internal_qpns_size();
}
inline void RdmaSessionRequest::clear_qpns() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qpns_.Clear();
}
inline ::uint32_t RdmaSessionRequest::qpns(int index) const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionRequest.qpns)
  return _internal_qpns().Get(index);
}
inline void RdmaSessionRequest::set_qpns(int index, ::uint32_t value) {
  _internal_mutable_qpns()->Set(index, value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionRequest.qpns)
}
inline void RdmaSessionRequest::add_qpns(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_qpns()->Add(value);
  // @@protoc_insertion_point(field_add:flashreduce_proto.RdmaSessionRequest.qpns)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& RdmaSessionRequest::qpns() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:flashreduce_proto.RdmaSessionRequest.qpns)
  return _internal_qpns();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* RdmaSessionRequest::mutable_qpns()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:flashreduce_proto.RdmaSessionRequest.qpns)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_qpns();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
RdmaSessionRequest::_internal_qpns() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.qpns_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* RdmaSessionRequest::_internal_mutable_qpns() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.qpns_;
}

// repeated uint32 psns = 10;
inline int RdmaSessionRequest::_internal_psns_size() const {
  return _internal_psns().size();
}
inline int RdmaSessionRequest::psns_size() const {
  return _internal_psns_size();
}
inline void RdmaSessionRequest::clear_psns() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.psns_.Clear();
}
inline ::uint32_t RdmaSessionRequest::psns(int index) const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionRequest.psns)
  return _internal_psns().Get(index);
}
inline void RdmaSessionRequest::set_psns(int index, ::uint32_t value) {
  _internal_mutable_psns()->Set(index, value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionRequest.psns)
}
inline void RdmaSessionRequest::add_psns(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_psns()->Add(value);
  // @@protoc_insertion_point(field_add:flashreduce_proto.RdmaSessionRequest.psns)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& RdmaSessionRequest::psns() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:flashreduce_proto.RdmaSessionRequest.psns)
  return _internal_psns();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* RdmaSessionRequest::mutable_psns()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:flashreduce_proto.RdmaSessionRequest.psns)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_psns();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
RdmaSessionRequest::_internal_psns() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.psns_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* RdmaSessionRequest::_internal_mutable_psns() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.psns_;
}

// -------------------------------------------------------------------

// RdmaSessionResponse

// uint64 session_id = 1;
inline void RdmaSessionResponse::clear_session_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_id_ = ::uint64_t{0u};
}
inline ::uint64_t RdmaSessionResponse::session_id() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionResponse.session_id)
  return _internal_session_id();
}
inline void RdmaSessionResponse::set_session_id(::uint64_t value) {
  _internal_set_session_id(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionResponse.session_id)
}
inline ::uint64_t RdmaSessionResponse::_internal_session_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.session_id_;
}
inline void RdmaSessionResponse::_internal_set_session_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_id_ = value;
}

// uint64 mac = 2;
inline void RdmaSessionResponse::clear_mac() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mac_ = ::uint64_t{0u};
}
inline ::uint64_t RdmaSessionResponse::mac() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionResponse.mac)
  return _internal_mac();
}
inline void RdmaSessionResponse::set_mac(::uint64_t value) {
  _internal_set_mac(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionResponse.mac)
}
inline ::uint64_t RdmaSessionResponse::_internal_mac() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.mac_;
}
inline void RdmaSessionResponse::_internal_set_mac(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mac_ = value;
}

// uint32 ipv4 = 3;
inline void RdmaSessionResponse::clear_ipv4() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ipv4_ = 0u;
}
inline ::uint32_t RdmaSessionResponse::ipv4() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionResponse.ipv4)
  return _internal_ipv4();
}
inline void RdmaSessionResponse::set_ipv4(::uint32_t value) {
  _internal_set_ipv4(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionResponse.ipv4)
}
inline ::uint32_t RdmaSessionResponse::_internal_ipv4() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ipv4_;
}
inline void RdmaSessionResponse::_internal_set_ipv4(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ipv4_ = value;
}

// uint32 rkey = 4;
inline void RdmaSessionResponse::clear_rkey() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rkey_ = 0u;
}
inline ::uint32_t RdmaSessionResponse::rkey() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionResponse.rkey)
  return _internal_rkey();
}
inline void RdmaSessionResponse::set_rkey(::uint32_t value) {
  _internal_set_rkey(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionResponse.rkey)
}
inline ::uint32_t RdmaSessionResponse::_internal_rkey() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rkey_;
}
inline void RdmaSessionResponse::_internal_set_rkey(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rkey_ = value;
}

// repeated uint32 qpns = 5;
inline int RdmaSessionResponse::_internal_qpns_size() const {
  return _internal_qpns().size();
}
inline int RdmaSessionResponse::qpns_size() const {
  return _internal_qpns_size();
}
inline void RdmaSessionResponse::clear_qpns() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qpns_.Clear();
}
inline ::uint32_t RdmaSessionResponse::qpns(int index) const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionResponse.qpns)
  return _internal_qpns().Get(index);
}
inline void RdmaSessionResponse::set_qpns(int index, ::uint32_t value) {
  _internal_mutable_qpns()->Set(index, value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionResponse.qpns)
}
inline void RdmaSessionResponse::add_qpns(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_qpns()->Add(value);
  // @@protoc_insertion_point(field_add:flashreduce_proto.RdmaSessionResponse.qpns)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& RdmaSessionResponse::qpns() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:flashreduce_proto.RdmaSessionResponse.qpns)
  return _internal_qpns();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* RdmaSessionResponse::mutable_qpns()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:flashreduce_proto.RdmaSessionResponse.qpns)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_qpns();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
RdmaSessionResponse::_internal_qpns() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.qpns_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* RdmaSessionResponse::_internal_mutable_qpns() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.qpns_;
}

// repeated uint32 psns = 6;
inline int RdmaSessionResponse::_internal_psns_size() const {
  return _internal_psns().size();
}
inline int RdmaSessionResponse::psns_size() const {
  return _internal_psns_size();
}
inline void RdmaSessionResponse::clear_psns() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.psns_.Clear();
}
inline ::uint32_t RdmaSessionResponse::psns(int index) const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionResponse.psns)
  return _internal_psns().Get(index);
}
inline void RdmaSessionResponse::set_psns(int index, ::uint32_t value) {
  _internal_mutable_psns()->Set(index, value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionResponse.psns)
}
inline void RdmaSessionResponse::add_psns(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_psns()->Add(value);
  // @@protoc_insertion_point(field_add:flashreduce_proto.RdmaSessionResponse.psns)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& RdmaSessionResponse::psns() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:flashreduce_proto.RdmaSessionResponse.psns)
  return _internal_psns();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* RdmaSessionResponse::mutable_psns()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:flashreduce_proto.RdmaSessionResponse.psns)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_psns();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
RdmaSessionResponse::_internal_psns() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.psns_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* RdmaSessionResponse::_internal_mutable_psns() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.psns_;
}

// -------------------------------------------------------------------

// BarrierRequest

// uint32 num_workers = 1;
inline void BarrierRequest::clear_num_workers() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_workers_ = 0u;
}
inline ::uint32_t BarrierRequest::num_workers() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.BarrierRequest.num_workers)
  return _internal_num_workers();
}
inline void BarrierRequest::set_num_workers(::uint32_t value) {
  _internal_set_num_workers(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.BarrierRequest.num_workers)
}
inline ::uint32_t BarrierRequest::_internal_num_workers() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num_workers_;
}
inline void BarrierRequest::_internal_set_num_workers(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_workers_ = value;
}

// -------------------------------------------------------------------

// BarrierResponse

// -------------------------------------------------------------------

// BroadcastRequest

// uint64 value = 1;
inline void BroadcastRequest::clear_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_ = ::uint64_t{0u};
}
inline ::uint64_t BroadcastRequest::value() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.BroadcastRequest.value)
  return _internal_value();
}
inline void BroadcastRequest::set_value(::uint64_t value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.BroadcastRequest.value)
}
inline ::uint64_t BroadcastRequest::_internal_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.value_;
}
inline void BroadcastRequest::_internal_set_value(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_ = value;
}

// uint32 rank = 2;
inline void BroadcastRequest::clear_rank() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rank_ = 0u;
}
inline ::uint32_t BroadcastRequest::rank() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.BroadcastRequest.rank)
  return _internal_rank();
}
inline void BroadcastRequest::set_rank(::uint32_t value) {
  _internal_set_rank(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.BroadcastRequest.rank)
}
inline ::uint32_t BroadcastRequest::_internal_rank() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rank_;
}
inline void BroadcastRequest::_internal_set_rank(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rank_ = value;
}

// uint32 num_workers = 3;
inline void BroadcastRequest::clear_num_workers() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_workers_ = 0u;
}
inline ::uint32_t BroadcastRequest::num_workers() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.BroadcastRequest.num_workers)
  return _internal_num_workers();
}
inline void BroadcastRequest::set_num_workers(::uint32_t value) {
  _internal_set_num_workers(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.BroadcastRequest.num_workers)
}
inline ::uint32_t BroadcastRequest::_internal_num_workers() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num_workers_;
}
inline void BroadcastRequest::_internal_set_num_workers(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_workers_ = value;
}

// uint32 root = 4;
inline void BroadcastRequest::clear_root() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.root_ = 0u;
}
inline ::uint32_t BroadcastRequest::root() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.BroadcastRequest.root)
  return _internal_root();
}
inline void BroadcastRequest::set_root(::uint32_t value) {
  _internal_set_root(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.BroadcastRequest.root)
}
inline ::uint32_t BroadcastRequest::_internal_root() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.root_;
}
inline void BroadcastRequest::_internal_set_root(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.root_ = value;
}

// -------------------------------------------------------------------

// BroadcastResponse

// uint64 value = 1;
inline void BroadcastResponse::clear_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_ = ::uint64_t{0u};
}
inline ::uint64_t BroadcastResponse::value() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.BroadcastResponse.value)
  return _internal_value();
}
inline void BroadcastResponse::set_value(::uint64_t value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.BroadcastResponse.value)
}
inline ::uint64_t BroadcastResponse::_internal_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.value_;
}
inline void BroadcastResponse::_internal_set_value(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace flashreduce_proto


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::flashreduce_proto::PacketSize> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::flashreduce_proto::PacketSize>() {
  return ::flashreduce_proto::PacketSize_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // flashreduce_2eproto_2epb_2eh
