// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: flashreduce.proto

#include "flashreduce.pb.h"
#include "flashreduce.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace flashreduce_proto {

static const char* Session_method_names[] = {
  "/flashreduce_proto.Session/RdmaSession",
};

std::unique_ptr< Session::Stub> Session::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Session::Stub> stub(new Session::Stub(channel, options));
  return stub;
}

Session::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RdmaSession_(Session_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Session::Stub::RdmaSession(::grpc::ClientContext* context, const ::flashreduce_proto::RdmaSessionRequest& request, ::flashreduce_proto::RdmaSessionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flashreduce_proto::RdmaSessionRequest, ::flashreduce_proto::RdmaSessionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RdmaSession_, context, request, response);
}

void Session::Stub::async::RdmaSession(::grpc::ClientContext* context, const ::flashreduce_proto::RdmaSessionRequest* request, ::flashreduce_proto::RdmaSessionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flashreduce_proto::RdmaSessionRequest, ::flashreduce_proto::RdmaSessionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RdmaSession_, context, request, response, std::move(f));
}

void Session::Stub::async::RdmaSession(::grpc::ClientContext* context, const ::flashreduce_proto::RdmaSessionRequest* request, ::flashreduce_proto::RdmaSessionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RdmaSession_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flashreduce_proto::RdmaSessionResponse>* Session::Stub::PrepareAsyncRdmaSessionRaw(::grpc::ClientContext* context, const ::flashreduce_proto::RdmaSessionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flashreduce_proto::RdmaSessionResponse, ::flashreduce_proto::RdmaSessionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RdmaSession_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flashreduce_proto::RdmaSessionResponse>* Session::Stub::AsyncRdmaSessionRaw(::grpc::ClientContext* context, const ::flashreduce_proto::RdmaSessionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRdmaSessionRaw(context, request, cq);
  result->StartCall();
  return result;
}

Session::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Session_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Session::Service, ::flashreduce_proto::RdmaSessionRequest, ::flashreduce_proto::RdmaSessionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Session::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flashreduce_proto::RdmaSessionRequest* req,
             ::flashreduce_proto::RdmaSessionResponse* resp) {
               return service->RdmaSession(ctx, req, resp);
             }, this)));
}

Session::Service::~Service() {
}

::grpc::Status Session::Service::RdmaSession(::grpc::ServerContext* context, const ::flashreduce_proto::RdmaSessionRequest* request, ::flashreduce_proto::RdmaSessionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* Sync_method_names[] = {
  "/flashreduce_proto.Sync/Barrier",
  "/flashreduce_proto.Sync/Broadcast",
};

std::unique_ptr< Sync::Stub> Sync::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Sync::Stub> stub(new Sync::Stub(channel, options));
  return stub;
}

Sync::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Barrier_(Sync_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Broadcast_(Sync_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Sync::Stub::Barrier(::grpc::ClientContext* context, const ::flashreduce_proto::BarrierRequest& request, ::flashreduce_proto::BarrierResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flashreduce_proto::BarrierRequest, ::flashreduce_proto::BarrierResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Barrier_, context, request, response);
}

void Sync::Stub::async::Barrier(::grpc::ClientContext* context, const ::flashreduce_proto::BarrierRequest* request, ::flashreduce_proto::BarrierResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flashreduce_proto::BarrierRequest, ::flashreduce_proto::BarrierResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Barrier_, context, request, response, std::move(f));
}

void Sync::Stub::async::Barrier(::grpc::ClientContext* context, const ::flashreduce_proto::BarrierRequest* request, ::flashreduce_proto::BarrierResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Barrier_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flashreduce_proto::BarrierResponse>* Sync::Stub::PrepareAsyncBarrierRaw(::grpc::ClientContext* context, const ::flashreduce_proto::BarrierRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flashreduce_proto::BarrierResponse, ::flashreduce_proto::BarrierRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Barrier_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flashreduce_proto::BarrierResponse>* Sync::Stub::AsyncBarrierRaw(::grpc::ClientContext* context, const ::flashreduce_proto::BarrierRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBarrierRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Sync::Stub::Broadcast(::grpc::ClientContext* context, const ::flashreduce_proto::BroadcastRequest& request, ::flashreduce_proto::BroadcastResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flashreduce_proto::BroadcastRequest, ::flashreduce_proto::BroadcastResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Broadcast_, context, request, response);
}

void Sync::Stub::async::Broadcast(::grpc::ClientContext* context, const ::flashreduce_proto::BroadcastRequest* request, ::flashreduce_proto::BroadcastResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flashreduce_proto::BroadcastRequest, ::flashreduce_proto::BroadcastResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Broadcast_, context, request, response, std::move(f));
}

void Sync::Stub::async::Broadcast(::grpc::ClientContext* context, const ::flashreduce_proto::BroadcastRequest* request, ::flashreduce_proto::BroadcastResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Broadcast_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flashreduce_proto::BroadcastResponse>* Sync::Stub::PrepareAsyncBroadcastRaw(::grpc::ClientContext* context, const ::flashreduce_proto::BroadcastRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flashreduce_proto::BroadcastResponse, ::flashreduce_proto::BroadcastRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Broadcast_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flashreduce_proto::BroadcastResponse>* Sync::Stub::AsyncBroadcastRaw(::grpc::ClientContext* context, const ::flashreduce_proto::BroadcastRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBroadcastRaw(context, request, cq);
  result->StartCall();
  return result;
}

Sync::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Sync_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Sync::Service, ::flashreduce_proto::BarrierRequest, ::flashreduce_proto::BarrierResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Sync::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flashreduce_proto::BarrierRequest* req,
             ::flashreduce_proto::BarrierResponse* resp) {
               return service->Barrier(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Sync_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Sync::Service, ::flashreduce_proto::BroadcastRequest, ::flashreduce_proto::BroadcastResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Sync::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flashreduce_proto::BroadcastRequest* req,
             ::flashreduce_proto::BroadcastResponse* resp) {
               return service->Broadcast(ctx, req, resp);
             }, this)));
}

Sync::Service::~Service() {
}

::grpc::Status Sync::Service::Barrier(::grpc::ServerContext* context, const ::flashreduce_proto::BarrierRequest* request, ::flashreduce_proto::BarrierResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Sync::Service::Broadcast(::grpc::ServerContext* context, const ::flashreduce_proto::BroadcastRequest* request, ::flashreduce_proto::BroadcastResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace flashreduce_proto

