// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: flashreduce.proto
// Protobuf C++ Version: 5.29.0

#ifndef flashreduce_2eproto_2epb_2eh
#define flashreduce_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_flashreduce_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_flashreduce_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_flashreduce_2eproto;
namespace flashreduce_proto {
class BarrierRequest;
struct BarrierRequestDefaultTypeInternal;
extern BarrierRequestDefaultTypeInternal _BarrierRequest_default_instance_;
class BarrierResponse;
struct BarrierResponseDefaultTypeInternal;
extern BarrierResponseDefaultTypeInternal _BarrierResponse_default_instance_;
class BroadcastRequest;
struct BroadcastRequestDefaultTypeInternal;
extern BroadcastRequestDefaultTypeInternal _BroadcastRequest_default_instance_;
class BroadcastResponse;
struct BroadcastResponseDefaultTypeInternal;
extern BroadcastResponseDefaultTypeInternal _BroadcastResponse_default_instance_;
class RdmaSessionRequest;
struct RdmaSessionRequestDefaultTypeInternal;
extern RdmaSessionRequestDefaultTypeInternal _RdmaSessionRequest_default_instance_;
class RdmaSessionResponse;
struct RdmaSessionResponseDefaultTypeInternal;
extern RdmaSessionResponseDefaultTypeInternal _RdmaSessionResponse_default_instance_;
}  // namespace flashreduce_proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace flashreduce_proto {

// ===================================================================


// -------------------------------------------------------------------

class RdmaSessionResponse final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:flashreduce_proto.RdmaSessionResponse) */ {
 public:
  inline RdmaSessionResponse() : RdmaSessionResponse(nullptr) {}
  ~RdmaSessionResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RdmaSessionResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RdmaSessionResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RdmaSessionResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline RdmaSessionResponse(const RdmaSessionResponse& from) : RdmaSessionResponse(nullptr, from) {}
  inline RdmaSessionResponse(RdmaSessionResponse&& from) noexcept
      : RdmaSessionResponse(nullptr, std::move(from)) {}
  inline RdmaSessionResponse& operator=(const RdmaSessionResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline RdmaSessionResponse& operator=(RdmaSessionResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RdmaSessionResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const RdmaSessionResponse* internal_default_instance() {
    return reinterpret_cast<const RdmaSessionResponse*>(
        &_RdmaSessionResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(RdmaSessionResponse& a, RdmaSessionResponse& b) { a.Swap(&b); }
  inline void Swap(RdmaSessionResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RdmaSessionResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RdmaSessionResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RdmaSessionResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RdmaSessionResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RdmaSessionResponse& from) { RdmaSessionResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RdmaSessionResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "flashreduce_proto.RdmaSessionResponse"; }

 protected:
  explicit RdmaSessionResponse(::google::protobuf::Arena* arena);
  RdmaSessionResponse(::google::protobuf::Arena* arena, const RdmaSessionResponse& from);
  RdmaSessionResponse(::google::protobuf::Arena* arena, RdmaSessionResponse&& from) noexcept
      : RdmaSessionResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRaddrFieldNumber = 3,
    kRkeyFieldNumber = 2,
    kQpnFieldNumber = 4,
    kPsnFieldNumber = 5,
    kLidFieldNumber = 15,
    kGidSubnetFieldNumber = 13,
    kGidIfaceFieldNumber = 14,
  };
  // uint64 raddr = 3;
  void clear_raddr() ;
  ::uint64_t raddr() const;
  void set_raddr(::uint64_t value);

  private:
  ::uint64_t _internal_raddr() const;
  void _internal_set_raddr(::uint64_t value);

  public:
  // uint32 rkey = 2;
  void clear_rkey() ;
  ::uint32_t rkey() const;
  void set_rkey(::uint32_t value);

  private:
  ::uint32_t _internal_rkey() const;
  void _internal_set_rkey(::uint32_t value);

  public:
  // uint32 qpn = 4;
  void clear_qpn() ;
  ::uint32_t qpn() const;
  void set_qpn(::uint32_t value);

  private:
  ::uint32_t _internal_qpn() const;
  void _internal_set_qpn(::uint32_t value);

  public:
  // uint32 psn = 5;
  void clear_psn() ;
  ::uint32_t psn() const;
  void set_psn(::uint32_t value);

  private:
  ::uint32_t _internal_psn() const;
  void _internal_set_psn(::uint32_t value);

  public:
  // uint32 lid = 15;
  void clear_lid() ;
  ::uint32_t lid() const;
  void set_lid(::uint32_t value);

  private:
  ::uint32_t _internal_lid() const;
  void _internal_set_lid(::uint32_t value);

  public:
  // uint64 gid_subnet = 13;
  void clear_gid_subnet() ;
  ::uint64_t gid_subnet() const;
  void set_gid_subnet(::uint64_t value);

  private:
  ::uint64_t _internal_gid_subnet() const;
  void _internal_set_gid_subnet(::uint64_t value);

  public:
  // uint64 gid_iface = 14;
  void clear_gid_iface() ;
  ::uint64_t gid_iface() const;
  void set_gid_iface(::uint64_t value);

  private:
  ::uint64_t _internal_gid_iface() const;
  void _internal_set_gid_iface(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:flashreduce_proto.RdmaSessionResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 7, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const RdmaSessionResponse& from_msg);
    ::uint64_t raddr_;
    ::uint32_t rkey_;
    ::uint32_t qpn_;
    ::uint32_t psn_;
    ::uint32_t lid_;
    ::uint64_t gid_subnet_;
    ::uint64_t gid_iface_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_flashreduce_2eproto;
};
// -------------------------------------------------------------------

class RdmaSessionRequest final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:flashreduce_proto.RdmaSessionRequest) */ {
 public:
  inline RdmaSessionRequest() : RdmaSessionRequest(nullptr) {}
  ~RdmaSessionRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RdmaSessionRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RdmaSessionRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RdmaSessionRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline RdmaSessionRequest(const RdmaSessionRequest& from) : RdmaSessionRequest(nullptr, from) {}
  inline RdmaSessionRequest(RdmaSessionRequest&& from) noexcept
      : RdmaSessionRequest(nullptr, std::move(from)) {}
  inline RdmaSessionRequest& operator=(const RdmaSessionRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline RdmaSessionRequest& operator=(RdmaSessionRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RdmaSessionRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const RdmaSessionRequest* internal_default_instance() {
    return reinterpret_cast<const RdmaSessionRequest*>(
        &_RdmaSessionRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RdmaSessionRequest& a, RdmaSessionRequest& b) { a.Swap(&b); }
  inline void Swap(RdmaSessionRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RdmaSessionRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RdmaSessionRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RdmaSessionRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RdmaSessionRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RdmaSessionRequest& from) { RdmaSessionRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RdmaSessionRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "flashreduce_proto.RdmaSessionRequest"; }

 protected:
  explicit RdmaSessionRequest(::google::protobuf::Arena* arena);
  RdmaSessionRequest(::google::protobuf::Arena* arena, const RdmaSessionRequest& from);
  RdmaSessionRequest(::google::protobuf::Arena* arena, RdmaSessionRequest&& from) noexcept
      : RdmaSessionRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSessionIdFieldNumber = 1,
    kRankFieldNumber = 2,
    kNumWorkersFieldNumber = 3,
    kRootFieldNumber = 4,
    kMacFieldNumber = 5,
    kIpv4FieldNumber = 6,
    kRkeyFieldNumber = 7,
    kRaddrFieldNumber = 8,
    kQpnFieldNumber = 9,
    kPsnFieldNumber = 10,
    kGidSubnetFieldNumber = 11,
    kGidIfaceFieldNumber = 12,
    kLidFieldNumber = 13,
  };
  // uint32 session_id = 1;
  void clear_session_id() ;
  ::uint32_t session_id() const;
  void set_session_id(::uint32_t value);

  private:
  ::uint32_t _internal_session_id() const;
  void _internal_set_session_id(::uint32_t value);

  public:
  // uint32 rank = 2;
  void clear_rank() ;
  ::uint32_t rank() const;
  void set_rank(::uint32_t value);

  private:
  ::uint32_t _internal_rank() const;
  void _internal_set_rank(::uint32_t value);

  public:
  // uint32 num_workers = 3;
  void clear_num_workers() ;
  ::uint32_t num_workers() const;
  void set_num_workers(::uint32_t value);

  private:
  ::uint32_t _internal_num_workers() const;
  void _internal_set_num_workers(::uint32_t value);

  public:
  // uint32 root = 4;
  void clear_root() ;
  ::uint32_t root() const;
  void set_root(::uint32_t value);

  private:
  ::uint32_t _internal_root() const;
  void _internal_set_root(::uint32_t value);

  public:
  // uint64 mac = 5;
  void clear_mac() ;
  ::uint64_t mac() const;
  void set_mac(::uint64_t value);

  private:
  ::uint64_t _internal_mac() const;
  void _internal_set_mac(::uint64_t value);

  public:
  // uint32 ipv4 = 6;
  void clear_ipv4() ;
  ::uint32_t ipv4() const;
  void set_ipv4(::uint32_t value);

  private:
  ::uint32_t _internal_ipv4() const;
  void _internal_set_ipv4(::uint32_t value);

  public:
  // uint32 rkey = 7;
  void clear_rkey() ;
  ::uint32_t rkey() const;
  void set_rkey(::uint32_t value);

  private:
  ::uint32_t _internal_rkey() const;
  void _internal_set_rkey(::uint32_t value);

  public:
  // uint64 raddr = 8;
  void clear_raddr() ;
  ::uint64_t raddr() const;
  void set_raddr(::uint64_t value);

  private:
  ::uint64_t _internal_raddr() const;
  void _internal_set_raddr(::uint64_t value);

  public:
  // uint32 qpn = 9;
  void clear_qpn() ;
  ::uint32_t qpn() const;
  void set_qpn(::uint32_t value);

  private:
  ::uint32_t _internal_qpn() const;
  void _internal_set_qpn(::uint32_t value);

  public:
  // uint32 psn = 10;
  void clear_psn() ;
  ::uint32_t psn() const;
  void set_psn(::uint32_t value);

  private:
  ::uint32_t _internal_psn() const;
  void _internal_set_psn(::uint32_t value);

  public:
  // uint64 gid_subnet = 11;
  void clear_gid_subnet() ;
  ::uint64_t gid_subnet() const;
  void set_gid_subnet(::uint64_t value);

  private:
  ::uint64_t _internal_gid_subnet() const;
  void _internal_set_gid_subnet(::uint64_t value);

  public:
  // uint64 gid_iface = 12;
  void clear_gid_iface() ;
  ::uint64_t gid_iface() const;
  void set_gid_iface(::uint64_t value);

  private:
  ::uint64_t _internal_gid_iface() const;
  void _internal_set_gid_iface(::uint64_t value);

  public:
  // uint32 lid = 13;
  void clear_lid() ;
  ::uint32_t lid() const;
  void set_lid(::uint32_t value);

  private:
  ::uint32_t _internal_lid() const;
  void _internal_set_lid(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:flashreduce_proto.RdmaSessionRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 13, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const RdmaSessionRequest& from_msg);
    ::uint32_t session_id_;
    ::uint32_t rank_;
    ::uint32_t num_workers_;
    ::uint32_t root_;
    ::uint64_t mac_;
    ::uint32_t ipv4_;
    ::uint32_t rkey_;
    ::uint64_t raddr_;
    ::uint32_t qpn_;
    ::uint32_t psn_;
    ::uint64_t gid_subnet_;
    ::uint64_t gid_iface_;
    ::uint32_t lid_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_flashreduce_2eproto;
};
// -------------------------------------------------------------------

class BroadcastResponse final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:flashreduce_proto.BroadcastResponse) */ {
 public:
  inline BroadcastResponse() : BroadcastResponse(nullptr) {}
  ~BroadcastResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BroadcastResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BroadcastResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BroadcastResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline BroadcastResponse(const BroadcastResponse& from) : BroadcastResponse(nullptr, from) {}
  inline BroadcastResponse(BroadcastResponse&& from) noexcept
      : BroadcastResponse(nullptr, std::move(from)) {}
  inline BroadcastResponse& operator=(const BroadcastResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline BroadcastResponse& operator=(BroadcastResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BroadcastResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const BroadcastResponse* internal_default_instance() {
    return reinterpret_cast<const BroadcastResponse*>(
        &_BroadcastResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(BroadcastResponse& a, BroadcastResponse& b) { a.Swap(&b); }
  inline void Swap(BroadcastResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BroadcastResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BroadcastResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BroadcastResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BroadcastResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BroadcastResponse& from) { BroadcastResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BroadcastResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "flashreduce_proto.BroadcastResponse"; }

 protected:
  explicit BroadcastResponse(::google::protobuf::Arena* arena);
  BroadcastResponse(::google::protobuf::Arena* arena, const BroadcastResponse& from);
  BroadcastResponse(::google::protobuf::Arena* arena, BroadcastResponse&& from) noexcept
      : BroadcastResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kValueFieldNumber = 1,
  };
  // uint64 value = 1;
  void clear_value() ;
  ::uint64_t value() const;
  void set_value(::uint64_t value);

  private:
  ::uint64_t _internal_value() const;
  void _internal_set_value(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:flashreduce_proto.BroadcastResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const BroadcastResponse& from_msg);
    ::uint64_t value_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_flashreduce_2eproto;
};
// -------------------------------------------------------------------

class BroadcastRequest final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:flashreduce_proto.BroadcastRequest) */ {
 public:
  inline BroadcastRequest() : BroadcastRequest(nullptr) {}
  ~BroadcastRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BroadcastRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BroadcastRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BroadcastRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline BroadcastRequest(const BroadcastRequest& from) : BroadcastRequest(nullptr, from) {}
  inline BroadcastRequest(BroadcastRequest&& from) noexcept
      : BroadcastRequest(nullptr, std::move(from)) {}
  inline BroadcastRequest& operator=(const BroadcastRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline BroadcastRequest& operator=(BroadcastRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BroadcastRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const BroadcastRequest* internal_default_instance() {
    return reinterpret_cast<const BroadcastRequest*>(
        &_BroadcastRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(BroadcastRequest& a, BroadcastRequest& b) { a.Swap(&b); }
  inline void Swap(BroadcastRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BroadcastRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BroadcastRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BroadcastRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BroadcastRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BroadcastRequest& from) { BroadcastRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BroadcastRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "flashreduce_proto.BroadcastRequest"; }

 protected:
  explicit BroadcastRequest(::google::protobuf::Arena* arena);
  BroadcastRequest(::google::protobuf::Arena* arena, const BroadcastRequest& from);
  BroadcastRequest(::google::protobuf::Arena* arena, BroadcastRequest&& from) noexcept
      : BroadcastRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kValueFieldNumber = 1,
    kRankFieldNumber = 2,
    kNumWorkersFieldNumber = 3,
    kRootFieldNumber = 4,
  };
  // uint64 value = 1;
  void clear_value() ;
  ::uint64_t value() const;
  void set_value(::uint64_t value);

  private:
  ::uint64_t _internal_value() const;
  void _internal_set_value(::uint64_t value);

  public:
  // uint32 rank = 2;
  void clear_rank() ;
  ::uint32_t rank() const;
  void set_rank(::uint32_t value);

  private:
  ::uint32_t _internal_rank() const;
  void _internal_set_rank(::uint32_t value);

  public:
  // uint32 num_workers = 3;
  void clear_num_workers() ;
  ::uint32_t num_workers() const;
  void set_num_workers(::uint32_t value);

  private:
  ::uint32_t _internal_num_workers() const;
  void _internal_set_num_workers(::uint32_t value);

  public:
  // uint32 root = 4;
  void clear_root() ;
  ::uint32_t root() const;
  void set_root(::uint32_t value);

  private:
  ::uint32_t _internal_root() const;
  void _internal_set_root(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:flashreduce_proto.BroadcastRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const BroadcastRequest& from_msg);
    ::uint64_t value_;
    ::uint32_t rank_;
    ::uint32_t num_workers_;
    ::uint32_t root_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_flashreduce_2eproto;
};
// -------------------------------------------------------------------

class BarrierResponse final
    : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:flashreduce_proto.BarrierResponse) */ {
 public:
  inline BarrierResponse() : BarrierResponse(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BarrierResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BarrierResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BarrierResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline BarrierResponse(const BarrierResponse& from) : BarrierResponse(nullptr, from) {}
  inline BarrierResponse(BarrierResponse&& from) noexcept
      : BarrierResponse(nullptr, std::move(from)) {}
  inline BarrierResponse& operator=(const BarrierResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline BarrierResponse& operator=(BarrierResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BarrierResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const BarrierResponse* internal_default_instance() {
    return reinterpret_cast<const BarrierResponse*>(
        &_BarrierResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(BarrierResponse& a, BarrierResponse& b) { a.Swap(&b); }
  inline void Swap(BarrierResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BarrierResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BarrierResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<BarrierResponse>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const BarrierResponse& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const BarrierResponse& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "flashreduce_proto.BarrierResponse"; }

 protected:
  explicit BarrierResponse(::google::protobuf::Arena* arena);
  BarrierResponse(::google::protobuf::Arena* arena, const BarrierResponse& from);
  BarrierResponse(::google::protobuf::Arena* arena, BarrierResponse&& from) noexcept
      : BarrierResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:flashreduce_proto.BarrierResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const BarrierResponse& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_flashreduce_2eproto;
};
// -------------------------------------------------------------------

class BarrierRequest final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:flashreduce_proto.BarrierRequest) */ {
 public:
  inline BarrierRequest() : BarrierRequest(nullptr) {}
  ~BarrierRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BarrierRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BarrierRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BarrierRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline BarrierRequest(const BarrierRequest& from) : BarrierRequest(nullptr, from) {}
  inline BarrierRequest(BarrierRequest&& from) noexcept
      : BarrierRequest(nullptr, std::move(from)) {}
  inline BarrierRequest& operator=(const BarrierRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline BarrierRequest& operator=(BarrierRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BarrierRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const BarrierRequest* internal_default_instance() {
    return reinterpret_cast<const BarrierRequest*>(
        &_BarrierRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(BarrierRequest& a, BarrierRequest& b) { a.Swap(&b); }
  inline void Swap(BarrierRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BarrierRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BarrierRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BarrierRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BarrierRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BarrierRequest& from) { BarrierRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BarrierRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "flashreduce_proto.BarrierRequest"; }

 protected:
  explicit BarrierRequest(::google::protobuf::Arena* arena);
  BarrierRequest(::google::protobuf::Arena* arena, const BarrierRequest& from);
  BarrierRequest(::google::protobuf::Arena* arena, BarrierRequest&& from) noexcept
      : BarrierRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNumWorkersFieldNumber = 1,
  };
  // uint32 num_workers = 1;
  void clear_num_workers() ;
  ::uint32_t num_workers() const;
  void set_num_workers(::uint32_t value);

  private:
  ::uint32_t _internal_num_workers() const;
  void _internal_set_num_workers(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:flashreduce_proto.BarrierRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const BarrierRequest& from_msg);
    ::uint32_t num_workers_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_flashreduce_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RdmaSessionRequest

// uint32 session_id = 1;
inline void RdmaSessionRequest::clear_session_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_id_ = 0u;
}
inline ::uint32_t RdmaSessionRequest::session_id() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionRequest.session_id)
  return _internal_session_id();
}
inline void RdmaSessionRequest::set_session_id(::uint32_t value) {
  _internal_set_session_id(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionRequest.session_id)
}
inline ::uint32_t RdmaSessionRequest::_internal_session_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.session_id_;
}
inline void RdmaSessionRequest::_internal_set_session_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_id_ = value;
}

// uint32 rank = 2;
inline void RdmaSessionRequest::clear_rank() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rank_ = 0u;
}
inline ::uint32_t RdmaSessionRequest::rank() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionRequest.rank)
  return _internal_rank();
}
inline void RdmaSessionRequest::set_rank(::uint32_t value) {
  _internal_set_rank(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionRequest.rank)
}
inline ::uint32_t RdmaSessionRequest::_internal_rank() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rank_;
}
inline void RdmaSessionRequest::_internal_set_rank(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rank_ = value;
}

// uint32 num_workers = 3;
inline void RdmaSessionRequest::clear_num_workers() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_workers_ = 0u;
}
inline ::uint32_t RdmaSessionRequest::num_workers() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionRequest.num_workers)
  return _internal_num_workers();
}
inline void RdmaSessionRequest::set_num_workers(::uint32_t value) {
  _internal_set_num_workers(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionRequest.num_workers)
}
inline ::uint32_t RdmaSessionRequest::_internal_num_workers() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num_workers_;
}
inline void RdmaSessionRequest::_internal_set_num_workers(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_workers_ = value;
}

// uint32 root = 4;
inline void RdmaSessionRequest::clear_root() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.root_ = 0u;
}
inline ::uint32_t RdmaSessionRequest::root() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionRequest.root)
  return _internal_root();
}
inline void RdmaSessionRequest::set_root(::uint32_t value) {
  _internal_set_root(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionRequest.root)
}
inline ::uint32_t RdmaSessionRequest::_internal_root() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.root_;
}
inline void RdmaSessionRequest::_internal_set_root(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.root_ = value;
}

// uint64 mac = 5;
inline void RdmaSessionRequest::clear_mac() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mac_ = ::uint64_t{0u};
}
inline ::uint64_t RdmaSessionRequest::mac() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionRequest.mac)
  return _internal_mac();
}
inline void RdmaSessionRequest::set_mac(::uint64_t value) {
  _internal_set_mac(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionRequest.mac)
}
inline ::uint64_t RdmaSessionRequest::_internal_mac() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.mac_;
}
inline void RdmaSessionRequest::_internal_set_mac(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mac_ = value;
}

// uint32 ipv4 = 6;
inline void RdmaSessionRequest::clear_ipv4() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ipv4_ = 0u;
}
inline ::uint32_t RdmaSessionRequest::ipv4() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionRequest.ipv4)
  return _internal_ipv4();
}
inline void RdmaSessionRequest::set_ipv4(::uint32_t value) {
  _internal_set_ipv4(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionRequest.ipv4)
}
inline ::uint32_t RdmaSessionRequest::_internal_ipv4() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ipv4_;
}
inline void RdmaSessionRequest::_internal_set_ipv4(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ipv4_ = value;
}

// uint32 rkey = 7;
inline void RdmaSessionRequest::clear_rkey() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rkey_ = 0u;
}
inline ::uint32_t RdmaSessionRequest::rkey() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionRequest.rkey)
  return _internal_rkey();
}
inline void RdmaSessionRequest::set_rkey(::uint32_t value) {
  _internal_set_rkey(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionRequest.rkey)
}
inline ::uint32_t RdmaSessionRequest::_internal_rkey() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rkey_;
}
inline void RdmaSessionRequest::_internal_set_rkey(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rkey_ = value;
}

// uint64 raddr = 8;
inline void RdmaSessionRequest::clear_raddr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.raddr_ = ::uint64_t{0u};
}
inline ::uint64_t RdmaSessionRequest::raddr() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionRequest.raddr)
  return _internal_raddr();
}
inline void RdmaSessionRequest::set_raddr(::uint64_t value) {
  _internal_set_raddr(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionRequest.raddr)
}
inline ::uint64_t RdmaSessionRequest::_internal_raddr() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.raddr_;
}
inline void RdmaSessionRequest::_internal_set_raddr(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.raddr_ = value;
}

// uint32 qpn = 9;
inline void RdmaSessionRequest::clear_qpn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qpn_ = 0u;
}
inline ::uint32_t RdmaSessionRequest::qpn() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionRequest.qpn)
  return _internal_qpn();
}
inline void RdmaSessionRequest::set_qpn(::uint32_t value) {
  _internal_set_qpn(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionRequest.qpn)
}
inline ::uint32_t RdmaSessionRequest::_internal_qpn() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.qpn_;
}
inline void RdmaSessionRequest::_internal_set_qpn(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qpn_ = value;
}

// uint32 psn = 10;
inline void RdmaSessionRequest::clear_psn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.psn_ = 0u;
}
inline ::uint32_t RdmaSessionRequest::psn() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionRequest.psn)
  return _internal_psn();
}
inline void RdmaSessionRequest::set_psn(::uint32_t value) {
  _internal_set_psn(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionRequest.psn)
}
inline ::uint32_t RdmaSessionRequest::_internal_psn() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.psn_;
}
inline void RdmaSessionRequest::_internal_set_psn(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.psn_ = value;
}

// uint64 gid_subnet = 11;
inline void RdmaSessionRequest::clear_gid_subnet() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gid_subnet_ = ::uint64_t{0u};
}
inline ::uint64_t RdmaSessionRequest::gid_subnet() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionRequest.gid_subnet)
  return _internal_gid_subnet();
}
inline void RdmaSessionRequest::set_gid_subnet(::uint64_t value) {
  _internal_set_gid_subnet(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionRequest.gid_subnet)
}
inline ::uint64_t RdmaSessionRequest::_internal_gid_subnet() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gid_subnet_;
}
inline void RdmaSessionRequest::_internal_set_gid_subnet(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gid_subnet_ = value;
}

// uint64 gid_iface = 12;
inline void RdmaSessionRequest::clear_gid_iface() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gid_iface_ = ::uint64_t{0u};
}
inline ::uint64_t RdmaSessionRequest::gid_iface() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionRequest.gid_iface)
  return _internal_gid_iface();
}
inline void RdmaSessionRequest::set_gid_iface(::uint64_t value) {
  _internal_set_gid_iface(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionRequest.gid_iface)
}
inline ::uint64_t RdmaSessionRequest::_internal_gid_iface() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gid_iface_;
}
inline void RdmaSessionRequest::_internal_set_gid_iface(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gid_iface_ = value;
}

// uint32 lid = 13;
inline void RdmaSessionRequest::clear_lid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lid_ = 0u;
}
inline ::uint32_t RdmaSessionRequest::lid() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionRequest.lid)
  return _internal_lid();
}
inline void RdmaSessionRequest::set_lid(::uint32_t value) {
  _internal_set_lid(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionRequest.lid)
}
inline ::uint32_t RdmaSessionRequest::_internal_lid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lid_;
}
inline void RdmaSessionRequest::_internal_set_lid(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lid_ = value;
}

// -------------------------------------------------------------------

// RdmaSessionResponse

// uint32 rkey = 2;
inline void RdmaSessionResponse::clear_rkey() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rkey_ = 0u;
}
inline ::uint32_t RdmaSessionResponse::rkey() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionResponse.rkey)
  return _internal_rkey();
}
inline void RdmaSessionResponse::set_rkey(::uint32_t value) {
  _internal_set_rkey(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionResponse.rkey)
}
inline ::uint32_t RdmaSessionResponse::_internal_rkey() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rkey_;
}
inline void RdmaSessionResponse::_internal_set_rkey(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rkey_ = value;
}

// uint64 raddr = 3;
inline void RdmaSessionResponse::clear_raddr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.raddr_ = ::uint64_t{0u};
}
inline ::uint64_t RdmaSessionResponse::raddr() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionResponse.raddr)
  return _internal_raddr();
}
inline void RdmaSessionResponse::set_raddr(::uint64_t value) {
  _internal_set_raddr(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionResponse.raddr)
}
inline ::uint64_t RdmaSessionResponse::_internal_raddr() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.raddr_;
}
inline void RdmaSessionResponse::_internal_set_raddr(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.raddr_ = value;
}

// uint32 qpn = 4;
inline void RdmaSessionResponse::clear_qpn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qpn_ = 0u;
}
inline ::uint32_t RdmaSessionResponse::qpn() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionResponse.qpn)
  return _internal_qpn();
}
inline void RdmaSessionResponse::set_qpn(::uint32_t value) {
  _internal_set_qpn(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionResponse.qpn)
}
inline ::uint32_t RdmaSessionResponse::_internal_qpn() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.qpn_;
}
inline void RdmaSessionResponse::_internal_set_qpn(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qpn_ = value;
}

// uint32 psn = 5;
inline void RdmaSessionResponse::clear_psn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.psn_ = 0u;
}
inline ::uint32_t RdmaSessionResponse::psn() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionResponse.psn)
  return _internal_psn();
}
inline void RdmaSessionResponse::set_psn(::uint32_t value) {
  _internal_set_psn(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionResponse.psn)
}
inline ::uint32_t RdmaSessionResponse::_internal_psn() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.psn_;
}
inline void RdmaSessionResponse::_internal_set_psn(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.psn_ = value;
}

// uint64 gid_subnet = 13;
inline void RdmaSessionResponse::clear_gid_subnet() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gid_subnet_ = ::uint64_t{0u};
}
inline ::uint64_t RdmaSessionResponse::gid_subnet() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionResponse.gid_subnet)
  return _internal_gid_subnet();
}
inline void RdmaSessionResponse::set_gid_subnet(::uint64_t value) {
  _internal_set_gid_subnet(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionResponse.gid_subnet)
}
inline ::uint64_t RdmaSessionResponse::_internal_gid_subnet() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gid_subnet_;
}
inline void RdmaSessionResponse::_internal_set_gid_subnet(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gid_subnet_ = value;
}

// uint64 gid_iface = 14;
inline void RdmaSessionResponse::clear_gid_iface() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gid_iface_ = ::uint64_t{0u};
}
inline ::uint64_t RdmaSessionResponse::gid_iface() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionResponse.gid_iface)
  return _internal_gid_iface();
}
inline void RdmaSessionResponse::set_gid_iface(::uint64_t value) {
  _internal_set_gid_iface(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionResponse.gid_iface)
}
inline ::uint64_t RdmaSessionResponse::_internal_gid_iface() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gid_iface_;
}
inline void RdmaSessionResponse::_internal_set_gid_iface(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gid_iface_ = value;
}

// uint32 lid = 15;
inline void RdmaSessionResponse::clear_lid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lid_ = 0u;
}
inline ::uint32_t RdmaSessionResponse::lid() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.RdmaSessionResponse.lid)
  return _internal_lid();
}
inline void RdmaSessionResponse::set_lid(::uint32_t value) {
  _internal_set_lid(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.RdmaSessionResponse.lid)
}
inline ::uint32_t RdmaSessionResponse::_internal_lid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lid_;
}
inline void RdmaSessionResponse::_internal_set_lid(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lid_ = value;
}

// -------------------------------------------------------------------

// BarrierRequest

// uint32 num_workers = 1;
inline void BarrierRequest::clear_num_workers() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_workers_ = 0u;
}
inline ::uint32_t BarrierRequest::num_workers() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.BarrierRequest.num_workers)
  return _internal_num_workers();
}
inline void BarrierRequest::set_num_workers(::uint32_t value) {
  _internal_set_num_workers(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.BarrierRequest.num_workers)
}
inline ::uint32_t BarrierRequest::_internal_num_workers() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num_workers_;
}
inline void BarrierRequest::_internal_set_num_workers(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_workers_ = value;
}

// -------------------------------------------------------------------

// BarrierResponse

// -------------------------------------------------------------------

// BroadcastRequest

// uint64 value = 1;
inline void BroadcastRequest::clear_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_ = ::uint64_t{0u};
}
inline ::uint64_t BroadcastRequest::value() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.BroadcastRequest.value)
  return _internal_value();
}
inline void BroadcastRequest::set_value(::uint64_t value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.BroadcastRequest.value)
}
inline ::uint64_t BroadcastRequest::_internal_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.value_;
}
inline void BroadcastRequest::_internal_set_value(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_ = value;
}

// uint32 rank = 2;
inline void BroadcastRequest::clear_rank() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rank_ = 0u;
}
inline ::uint32_t BroadcastRequest::rank() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.BroadcastRequest.rank)
  return _internal_rank();
}
inline void BroadcastRequest::set_rank(::uint32_t value) {
  _internal_set_rank(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.BroadcastRequest.rank)
}
inline ::uint32_t BroadcastRequest::_internal_rank() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rank_;
}
inline void BroadcastRequest::_internal_set_rank(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rank_ = value;
}

// uint32 num_workers = 3;
inline void BroadcastRequest::clear_num_workers() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_workers_ = 0u;
}
inline ::uint32_t BroadcastRequest::num_workers() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.BroadcastRequest.num_workers)
  return _internal_num_workers();
}
inline void BroadcastRequest::set_num_workers(::uint32_t value) {
  _internal_set_num_workers(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.BroadcastRequest.num_workers)
}
inline ::uint32_t BroadcastRequest::_internal_num_workers() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num_workers_;
}
inline void BroadcastRequest::_internal_set_num_workers(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_workers_ = value;
}

// uint32 root = 4;
inline void BroadcastRequest::clear_root() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.root_ = 0u;
}
inline ::uint32_t BroadcastRequest::root() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.BroadcastRequest.root)
  return _internal_root();
}
inline void BroadcastRequest::set_root(::uint32_t value) {
  _internal_set_root(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.BroadcastRequest.root)
}
inline ::uint32_t BroadcastRequest::_internal_root() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.root_;
}
inline void BroadcastRequest::_internal_set_root(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.root_ = value;
}

// -------------------------------------------------------------------

// BroadcastResponse

// uint64 value = 1;
inline void BroadcastResponse::clear_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_ = ::uint64_t{0u};
}
inline ::uint64_t BroadcastResponse::value() const {
  // @@protoc_insertion_point(field_get:flashreduce_proto.BroadcastResponse.value)
  return _internal_value();
}
inline void BroadcastResponse::set_value(::uint64_t value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:flashreduce_proto.BroadcastResponse.value)
}
inline ::uint64_t BroadcastResponse::_internal_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.value_;
}
inline void BroadcastResponse::_internal_set_value(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace flashreduce_proto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // flashreduce_2eproto_2epb_2eh
