// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: flashreduce.proto
// Protobuf C++ Version: 5.29.0

#include "flashreduce.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace flashreduce_proto {

inline constexpr RdmaSessionResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : qpns_{},
        _qpns_cached_byte_size_{0},
        psns_{},
        _psns_cached_byte_size_{0},
        session_id_{::uint64_t{0u}},
        mac_{::uint64_t{0u}},
        ipv4_{0u},
        rkey_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RdmaSessionResponse::RdmaSessionResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RdmaSessionResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RdmaSessionResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RdmaSessionResponseDefaultTypeInternal() {}
  union {
    RdmaSessionResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RdmaSessionResponseDefaultTypeInternal _RdmaSessionResponse_default_instance_;

inline constexpr RdmaSessionRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : qpns_{},
        _qpns_cached_byte_size_{0},
        psns_{},
        _psns_cached_byte_size_{0},
        session_id_{0u},
        rank_{0u},
        mac_{::uint64_t{0u}},
        num_workers_{0u},
        ipv4_{0u},
        rkey_{0u},
        packet_size_{static_cast< ::flashreduce_proto::PacketSize >(0)},
        message_size_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RdmaSessionRequest::RdmaSessionRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RdmaSessionRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RdmaSessionRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RdmaSessionRequestDefaultTypeInternal() {}
  union {
    RdmaSessionRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RdmaSessionRequestDefaultTypeInternal _RdmaSessionRequest_default_instance_;

inline constexpr BroadcastResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BroadcastResponse::BroadcastResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BroadcastResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BroadcastResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BroadcastResponseDefaultTypeInternal() {}
  union {
    BroadcastResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BroadcastResponseDefaultTypeInternal _BroadcastResponse_default_instance_;

inline constexpr BroadcastRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_{::uint64_t{0u}},
        rank_{0u},
        num_workers_{0u},
        root_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BroadcastRequest::BroadcastRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BroadcastRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BroadcastRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BroadcastRequestDefaultTypeInternal() {}
  union {
    BroadcastRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BroadcastRequestDefaultTypeInternal _BroadcastRequest_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR BarrierResponse::BarrierResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct BarrierResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BarrierResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BarrierResponseDefaultTypeInternal() {}
  union {
    BarrierResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BarrierResponseDefaultTypeInternal _BarrierResponse_default_instance_;

inline constexpr BarrierRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : num_workers_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BarrierRequest::BarrierRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BarrierRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BarrierRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BarrierRequestDefaultTypeInternal() {}
  union {
    BarrierRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BarrierRequestDefaultTypeInternal _BarrierRequest_default_instance_;
}  // namespace flashreduce_proto
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_flashreduce_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_flashreduce_2eproto = nullptr;
const ::uint32_t
    TableStruct_flashreduce_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::RdmaSessionRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::RdmaSessionRequest, _impl_.session_id_),
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::RdmaSessionRequest, _impl_.rank_),
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::RdmaSessionRequest, _impl_.num_workers_),
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::RdmaSessionRequest, _impl_.mac_),
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::RdmaSessionRequest, _impl_.ipv4_),
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::RdmaSessionRequest, _impl_.rkey_),
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::RdmaSessionRequest, _impl_.packet_size_),
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::RdmaSessionRequest, _impl_.message_size_),
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::RdmaSessionRequest, _impl_.qpns_),
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::RdmaSessionRequest, _impl_.psns_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::RdmaSessionResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::RdmaSessionResponse, _impl_.session_id_),
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::RdmaSessionResponse, _impl_.mac_),
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::RdmaSessionResponse, _impl_.ipv4_),
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::RdmaSessionResponse, _impl_.rkey_),
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::RdmaSessionResponse, _impl_.qpns_),
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::RdmaSessionResponse, _impl_.psns_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::BarrierRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::BarrierRequest, _impl_.num_workers_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::BarrierResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::BroadcastRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::BroadcastRequest, _impl_.value_),
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::BroadcastRequest, _impl_.rank_),
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::BroadcastRequest, _impl_.num_workers_),
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::BroadcastRequest, _impl_.root_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::BroadcastResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::flashreduce_proto::BroadcastResponse, _impl_.value_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::flashreduce_proto::RdmaSessionRequest)},
        {18, -1, -1, sizeof(::flashreduce_proto::RdmaSessionResponse)},
        {32, -1, -1, sizeof(::flashreduce_proto::BarrierRequest)},
        {41, -1, -1, sizeof(::flashreduce_proto::BarrierResponse)},
        {49, -1, -1, sizeof(::flashreduce_proto::BroadcastRequest)},
        {61, -1, -1, sizeof(::flashreduce_proto::BroadcastResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::flashreduce_proto::_RdmaSessionRequest_default_instance_._instance,
    &::flashreduce_proto::_RdmaSessionResponse_default_instance_._instance,
    &::flashreduce_proto::_BarrierRequest_default_instance_._instance,
    &::flashreduce_proto::_BarrierResponse_default_instance_._instance,
    &::flashreduce_proto::_BroadcastRequest_default_instance_._instance,
    &::flashreduce_proto::_BroadcastResponse_default_instance_._instance,
};
const char descriptor_table_protodef_flashreduce_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021flashreduce.proto\022\021flashreduce_proto\"\332"
    "\001\n\022RdmaSessionRequest\022\022\n\nsession_id\030\001 \001("
    "\r\022\014\n\004rank\030\002 \001(\r\022\023\n\013num_workers\030\003 \001(\r\022\013\n\003"
    "mac\030\004 \001(\004\022\014\n\004ipv4\030\005 \001(\r\022\014\n\004rkey\030\006 \001(\r\0222\n"
    "\013packet_size\030\007 \001(\0162\035.flashreduce_proto.P"
    "acketSize\022\024\n\014message_size\030\010 \001(\r\022\014\n\004qpns\030"
    "\t \003(\r\022\014\n\004psns\030\n \003(\r\"n\n\023RdmaSessionRespon"
    "se\022\022\n\nsession_id\030\001 \001(\004\022\013\n\003mac\030\002 \001(\004\022\014\n\004i"
    "pv4\030\003 \001(\r\022\014\n\004rkey\030\004 \001(\r\022\014\n\004qpns\030\005 \003(\r\022\014\n"
    "\004psns\030\006 \003(\r\"%\n\016BarrierRequest\022\023\n\013num_wor"
    "kers\030\001 \001(\r\"\021\n\017BarrierResponse\"R\n\020Broadca"
    "stRequest\022\r\n\005value\030\001 \001(\004\022\014\n\004rank\030\002 \001(\r\022\023"
    "\n\013num_workers\030\003 \001(\r\022\014\n\004root\030\004 \001(\r\"\"\n\021Bro"
    "adcastResponse\022\r\n\005value\030\001 \001(\004*\'\n\nPacketS"
    "ize\022\013\n\007MTU_256\020\000\022\014\n\010MTU_1024\020\0012i\n\007Sessio"
    "n\022^\n\013RdmaSession\022%.flashreduce_proto.Rdm"
    "aSessionRequest\032&.flashreduce_proto.Rdma"
    "SessionResponse\"\0002\264\001\n\004Sync\022R\n\007Barrier\022!."
    "flashreduce_proto.BarrierRequest\032\".flash"
    "reduce_proto.BarrierResponse\"\000\022X\n\tBroadc"
    "ast\022#.flashreduce_proto.BroadcastRequest"
    "\032$.flashreduce_proto.BroadcastResponse\"\000"
    "b\006proto3"
};
static ::absl::once_flag descriptor_table_flashreduce_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_flashreduce_2eproto = {
    false,
    false,
    888,
    descriptor_table_protodef_flashreduce_2eproto,
    "flashreduce.proto",
    &descriptor_table_flashreduce_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_flashreduce_2eproto::offsets,
    file_level_enum_descriptors_flashreduce_2eproto,
    file_level_service_descriptors_flashreduce_2eproto,
};
namespace flashreduce_proto {
const ::google::protobuf::EnumDescriptor* PacketSize_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_flashreduce_2eproto);
  return file_level_enum_descriptors_flashreduce_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t PacketSize_internal_data_[] = {
    131072u, 0u, };
bool PacketSize_IsValid(int value) {
  return 0 <= value && value <= 1;
}
// ===================================================================

class RdmaSessionRequest::_Internal {
 public:
};

RdmaSessionRequest::RdmaSessionRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:flashreduce_proto.RdmaSessionRequest)
}
inline PROTOBUF_NDEBUG_INLINE RdmaSessionRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::flashreduce_proto::RdmaSessionRequest& from_msg)
      : qpns_{visibility, arena, from.qpns_},
        _qpns_cached_byte_size_{0},
        psns_{visibility, arena, from.psns_},
        _psns_cached_byte_size_{0},
        _cached_size_{0} {}

RdmaSessionRequest::RdmaSessionRequest(
    ::google::protobuf::Arena* arena,
    const RdmaSessionRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RdmaSessionRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, session_id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, session_id_),
           offsetof(Impl_, message_size_) -
               offsetof(Impl_, session_id_) +
               sizeof(Impl_::message_size_));

  // @@protoc_insertion_point(copy_constructor:flashreduce_proto.RdmaSessionRequest)
}
inline PROTOBUF_NDEBUG_INLINE RdmaSessionRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : qpns_{visibility, arena},
        _qpns_cached_byte_size_{0},
        psns_{visibility, arena},
        _psns_cached_byte_size_{0},
        _cached_size_{0} {}

inline void RdmaSessionRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, session_id_),
           0,
           offsetof(Impl_, message_size_) -
               offsetof(Impl_, session_id_) +
               sizeof(Impl_::message_size_));
}
RdmaSessionRequest::~RdmaSessionRequest() {
  // @@protoc_insertion_point(destructor:flashreduce_proto.RdmaSessionRequest)
  SharedDtor(*this);
}
inline void RdmaSessionRequest::SharedDtor(MessageLite& self) {
  RdmaSessionRequest& this_ = static_cast<RdmaSessionRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* RdmaSessionRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) RdmaSessionRequest(arena);
}
constexpr auto RdmaSessionRequest::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.qpns_) +
          decltype(RdmaSessionRequest::_impl_.qpns_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.psns_) +
          decltype(RdmaSessionRequest::_impl_.psns_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(RdmaSessionRequest), alignof(RdmaSessionRequest), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&RdmaSessionRequest::PlacementNew_,
                                 sizeof(RdmaSessionRequest),
                                 alignof(RdmaSessionRequest));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull RdmaSessionRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_RdmaSessionRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &RdmaSessionRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<RdmaSessionRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &RdmaSessionRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<RdmaSessionRequest>(), &RdmaSessionRequest::ByteSizeLong,
            &RdmaSessionRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_._cached_size_),
        false,
    },
    &RdmaSessionRequest::kDescriptorMethods,
    &descriptor_table_flashreduce_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* RdmaSessionRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 10, 0, 0, 2> RdmaSessionRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    10, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966272,  // skipmap
    offsetof(decltype(_table_), field_entries),
    10,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::flashreduce_proto::RdmaSessionRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 session_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RdmaSessionRequest, _impl_.session_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.session_id_)}},
    // uint32 rank = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RdmaSessionRequest, _impl_.rank_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.rank_)}},
    // uint32 num_workers = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RdmaSessionRequest, _impl_.num_workers_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.num_workers_)}},
    // uint64 mac = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(RdmaSessionRequest, _impl_.mac_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.mac_)}},
    // uint32 ipv4 = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RdmaSessionRequest, _impl_.ipv4_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.ipv4_)}},
    // uint32 rkey = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RdmaSessionRequest, _impl_.rkey_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.rkey_)}},
    // .flashreduce_proto.PacketSize packet_size = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RdmaSessionRequest, _impl_.packet_size_), 63>(),
     {56, 63, 0, PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.packet_size_)}},
    // uint32 message_size = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RdmaSessionRequest, _impl_.message_size_), 63>(),
     {64, 63, 0, PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.message_size_)}},
    // repeated uint32 qpns = 9;
    {::_pbi::TcParser::FastV32P1,
     {74, 63, 0, PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.qpns_)}},
    // repeated uint32 psns = 10;
    {::_pbi::TcParser::FastV32P1,
     {82, 63, 0, PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.psns_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 session_id = 1;
    {PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.session_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 rank = 2;
    {PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.rank_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 num_workers = 3;
    {PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.num_workers_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint64 mac = 4;
    {PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.mac_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint32 ipv4 = 5;
    {PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.ipv4_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 rkey = 6;
    {PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.rkey_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // .flashreduce_proto.PacketSize packet_size = 7;
    {PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.packet_size_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // uint32 message_size = 8;
    {PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.message_size_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // repeated uint32 qpns = 9;
    {PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.qpns_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
    // repeated uint32 psns = 10;
    {PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.psns_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void RdmaSessionRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:flashreduce_proto.RdmaSessionRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.qpns_.Clear();
  _impl_.psns_.Clear();
  ::memset(&_impl_.session_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.message_size_) -
      reinterpret_cast<char*>(&_impl_.session_id_)) + sizeof(_impl_.message_size_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* RdmaSessionRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const RdmaSessionRequest& this_ = static_cast<const RdmaSessionRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* RdmaSessionRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const RdmaSessionRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:flashreduce_proto.RdmaSessionRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 session_id = 1;
          if (this_._internal_session_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_session_id(), target);
          }

          // uint32 rank = 2;
          if (this_._internal_rank() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_rank(), target);
          }

          // uint32 num_workers = 3;
          if (this_._internal_num_workers() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                3, this_._internal_num_workers(), target);
          }

          // uint64 mac = 4;
          if (this_._internal_mac() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                4, this_._internal_mac(), target);
          }

          // uint32 ipv4 = 5;
          if (this_._internal_ipv4() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                5, this_._internal_ipv4(), target);
          }

          // uint32 rkey = 6;
          if (this_._internal_rkey() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                6, this_._internal_rkey(), target);
          }

          // .flashreduce_proto.PacketSize packet_size = 7;
          if (this_._internal_packet_size() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                7, this_._internal_packet_size(), target);
          }

          // uint32 message_size = 8;
          if (this_._internal_message_size() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                8, this_._internal_message_size(), target);
          }

          // repeated uint32 qpns = 9;
          {
            int byte_size = this_._impl_._qpns_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteUInt32Packed(
                  9, this_._internal_qpns(), byte_size, target);
            }
          }

          // repeated uint32 psns = 10;
          {
            int byte_size = this_._impl_._psns_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteUInt32Packed(
                  10, this_._internal_psns(), byte_size, target);
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:flashreduce_proto.RdmaSessionRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t RdmaSessionRequest::ByteSizeLong(const MessageLite& base) {
          const RdmaSessionRequest& this_ = static_cast<const RdmaSessionRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t RdmaSessionRequest::ByteSizeLong() const {
          const RdmaSessionRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:flashreduce_proto.RdmaSessionRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated uint32 qpns = 9;
            {
              total_size +=
                  ::_pbi::WireFormatLite::UInt32SizeWithPackedTagSize(
                      this_._internal_qpns(), 1,
                      this_._impl_._qpns_cached_byte_size_);
            }
            // repeated uint32 psns = 10;
            {
              total_size +=
                  ::_pbi::WireFormatLite::UInt32SizeWithPackedTagSize(
                      this_._internal_psns(), 1,
                      this_._impl_._psns_cached_byte_size_);
            }
          }
           {
            // uint32 session_id = 1;
            if (this_._internal_session_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_session_id());
            }
            // uint32 rank = 2;
            if (this_._internal_rank() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_rank());
            }
            // uint64 mac = 4;
            if (this_._internal_mac() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_mac());
            }
            // uint32 num_workers = 3;
            if (this_._internal_num_workers() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_num_workers());
            }
            // uint32 ipv4 = 5;
            if (this_._internal_ipv4() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_ipv4());
            }
            // uint32 rkey = 6;
            if (this_._internal_rkey() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_rkey());
            }
            // .flashreduce_proto.PacketSize packet_size = 7;
            if (this_._internal_packet_size() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_packet_size());
            }
            // uint32 message_size = 8;
            if (this_._internal_message_size() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_message_size());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void RdmaSessionRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RdmaSessionRequest*>(&to_msg);
  auto& from = static_cast<const RdmaSessionRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:flashreduce_proto.RdmaSessionRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_qpns()->MergeFrom(from._internal_qpns());
  _this->_internal_mutable_psns()->MergeFrom(from._internal_psns());
  if (from._internal_session_id() != 0) {
    _this->_impl_.session_id_ = from._impl_.session_id_;
  }
  if (from._internal_rank() != 0) {
    _this->_impl_.rank_ = from._impl_.rank_;
  }
  if (from._internal_mac() != 0) {
    _this->_impl_.mac_ = from._impl_.mac_;
  }
  if (from._internal_num_workers() != 0) {
    _this->_impl_.num_workers_ = from._impl_.num_workers_;
  }
  if (from._internal_ipv4() != 0) {
    _this->_impl_.ipv4_ = from._impl_.ipv4_;
  }
  if (from._internal_rkey() != 0) {
    _this->_impl_.rkey_ = from._impl_.rkey_;
  }
  if (from._internal_packet_size() != 0) {
    _this->_impl_.packet_size_ = from._impl_.packet_size_;
  }
  if (from._internal_message_size() != 0) {
    _this->_impl_.message_size_ = from._impl_.message_size_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RdmaSessionRequest::CopyFrom(const RdmaSessionRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:flashreduce_proto.RdmaSessionRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RdmaSessionRequest::InternalSwap(RdmaSessionRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.qpns_.InternalSwap(&other->_impl_.qpns_);
  _impl_.psns_.InternalSwap(&other->_impl_.psns_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.message_size_)
      + sizeof(RdmaSessionRequest::_impl_.message_size_)
      - PROTOBUF_FIELD_OFFSET(RdmaSessionRequest, _impl_.session_id_)>(
          reinterpret_cast<char*>(&_impl_.session_id_),
          reinterpret_cast<char*>(&other->_impl_.session_id_));
}

::google::protobuf::Metadata RdmaSessionRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RdmaSessionResponse::_Internal {
 public:
};

RdmaSessionResponse::RdmaSessionResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:flashreduce_proto.RdmaSessionResponse)
}
inline PROTOBUF_NDEBUG_INLINE RdmaSessionResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::flashreduce_proto::RdmaSessionResponse& from_msg)
      : qpns_{visibility, arena, from.qpns_},
        _qpns_cached_byte_size_{0},
        psns_{visibility, arena, from.psns_},
        _psns_cached_byte_size_{0},
        _cached_size_{0} {}

RdmaSessionResponse::RdmaSessionResponse(
    ::google::protobuf::Arena* arena,
    const RdmaSessionResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RdmaSessionResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, session_id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, session_id_),
           offsetof(Impl_, rkey_) -
               offsetof(Impl_, session_id_) +
               sizeof(Impl_::rkey_));

  // @@protoc_insertion_point(copy_constructor:flashreduce_proto.RdmaSessionResponse)
}
inline PROTOBUF_NDEBUG_INLINE RdmaSessionResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : qpns_{visibility, arena},
        _qpns_cached_byte_size_{0},
        psns_{visibility, arena},
        _psns_cached_byte_size_{0},
        _cached_size_{0} {}

inline void RdmaSessionResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, session_id_),
           0,
           offsetof(Impl_, rkey_) -
               offsetof(Impl_, session_id_) +
               sizeof(Impl_::rkey_));
}
RdmaSessionResponse::~RdmaSessionResponse() {
  // @@protoc_insertion_point(destructor:flashreduce_proto.RdmaSessionResponse)
  SharedDtor(*this);
}
inline void RdmaSessionResponse::SharedDtor(MessageLite& self) {
  RdmaSessionResponse& this_ = static_cast<RdmaSessionResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* RdmaSessionResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) RdmaSessionResponse(arena);
}
constexpr auto RdmaSessionResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(RdmaSessionResponse, _impl_.qpns_) +
          decltype(RdmaSessionResponse::_impl_.qpns_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(RdmaSessionResponse, _impl_.psns_) +
          decltype(RdmaSessionResponse::_impl_.psns_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(RdmaSessionResponse), alignof(RdmaSessionResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&RdmaSessionResponse::PlacementNew_,
                                 sizeof(RdmaSessionResponse),
                                 alignof(RdmaSessionResponse));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull RdmaSessionResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_RdmaSessionResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &RdmaSessionResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<RdmaSessionResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &RdmaSessionResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<RdmaSessionResponse>(), &RdmaSessionResponse::ByteSizeLong,
            &RdmaSessionResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(RdmaSessionResponse, _impl_._cached_size_),
        false,
    },
    &RdmaSessionResponse::kDescriptorMethods,
    &descriptor_table_flashreduce_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* RdmaSessionResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 0, 2> RdmaSessionResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::flashreduce_proto::RdmaSessionResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint64 session_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(RdmaSessionResponse, _impl_.session_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RdmaSessionResponse, _impl_.session_id_)}},
    // uint64 mac = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(RdmaSessionResponse, _impl_.mac_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(RdmaSessionResponse, _impl_.mac_)}},
    // uint32 ipv4 = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RdmaSessionResponse, _impl_.ipv4_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(RdmaSessionResponse, _impl_.ipv4_)}},
    // uint32 rkey = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RdmaSessionResponse, _impl_.rkey_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(RdmaSessionResponse, _impl_.rkey_)}},
    // repeated uint32 qpns = 5;
    {::_pbi::TcParser::FastV32P1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(RdmaSessionResponse, _impl_.qpns_)}},
    // repeated uint32 psns = 6;
    {::_pbi::TcParser::FastV32P1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(RdmaSessionResponse, _impl_.psns_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 session_id = 1;
    {PROTOBUF_FIELD_OFFSET(RdmaSessionResponse, _impl_.session_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint64 mac = 2;
    {PROTOBUF_FIELD_OFFSET(RdmaSessionResponse, _impl_.mac_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint32 ipv4 = 3;
    {PROTOBUF_FIELD_OFFSET(RdmaSessionResponse, _impl_.ipv4_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 rkey = 4;
    {PROTOBUF_FIELD_OFFSET(RdmaSessionResponse, _impl_.rkey_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // repeated uint32 qpns = 5;
    {PROTOBUF_FIELD_OFFSET(RdmaSessionResponse, _impl_.qpns_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
    // repeated uint32 psns = 6;
    {PROTOBUF_FIELD_OFFSET(RdmaSessionResponse, _impl_.psns_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void RdmaSessionResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:flashreduce_proto.RdmaSessionResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.qpns_.Clear();
  _impl_.psns_.Clear();
  ::memset(&_impl_.session_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.rkey_) -
      reinterpret_cast<char*>(&_impl_.session_id_)) + sizeof(_impl_.rkey_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* RdmaSessionResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const RdmaSessionResponse& this_ = static_cast<const RdmaSessionResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* RdmaSessionResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const RdmaSessionResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:flashreduce_proto.RdmaSessionResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 session_id = 1;
          if (this_._internal_session_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_session_id(), target);
          }

          // uint64 mac = 2;
          if (this_._internal_mac() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                2, this_._internal_mac(), target);
          }

          // uint32 ipv4 = 3;
          if (this_._internal_ipv4() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                3, this_._internal_ipv4(), target);
          }

          // uint32 rkey = 4;
          if (this_._internal_rkey() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                4, this_._internal_rkey(), target);
          }

          // repeated uint32 qpns = 5;
          {
            int byte_size = this_._impl_._qpns_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteUInt32Packed(
                  5, this_._internal_qpns(), byte_size, target);
            }
          }

          // repeated uint32 psns = 6;
          {
            int byte_size = this_._impl_._psns_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteUInt32Packed(
                  6, this_._internal_psns(), byte_size, target);
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:flashreduce_proto.RdmaSessionResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t RdmaSessionResponse::ByteSizeLong(const MessageLite& base) {
          const RdmaSessionResponse& this_ = static_cast<const RdmaSessionResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t RdmaSessionResponse::ByteSizeLong() const {
          const RdmaSessionResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:flashreduce_proto.RdmaSessionResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated uint32 qpns = 5;
            {
              total_size +=
                  ::_pbi::WireFormatLite::UInt32SizeWithPackedTagSize(
                      this_._internal_qpns(), 1,
                      this_._impl_._qpns_cached_byte_size_);
            }
            // repeated uint32 psns = 6;
            {
              total_size +=
                  ::_pbi::WireFormatLite::UInt32SizeWithPackedTagSize(
                      this_._internal_psns(), 1,
                      this_._impl_._psns_cached_byte_size_);
            }
          }
           {
            // uint64 session_id = 1;
            if (this_._internal_session_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_session_id());
            }
            // uint64 mac = 2;
            if (this_._internal_mac() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_mac());
            }
            // uint32 ipv4 = 3;
            if (this_._internal_ipv4() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_ipv4());
            }
            // uint32 rkey = 4;
            if (this_._internal_rkey() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_rkey());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void RdmaSessionResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RdmaSessionResponse*>(&to_msg);
  auto& from = static_cast<const RdmaSessionResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:flashreduce_proto.RdmaSessionResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_qpns()->MergeFrom(from._internal_qpns());
  _this->_internal_mutable_psns()->MergeFrom(from._internal_psns());
  if (from._internal_session_id() != 0) {
    _this->_impl_.session_id_ = from._impl_.session_id_;
  }
  if (from._internal_mac() != 0) {
    _this->_impl_.mac_ = from._impl_.mac_;
  }
  if (from._internal_ipv4() != 0) {
    _this->_impl_.ipv4_ = from._impl_.ipv4_;
  }
  if (from._internal_rkey() != 0) {
    _this->_impl_.rkey_ = from._impl_.rkey_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RdmaSessionResponse::CopyFrom(const RdmaSessionResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:flashreduce_proto.RdmaSessionResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RdmaSessionResponse::InternalSwap(RdmaSessionResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.qpns_.InternalSwap(&other->_impl_.qpns_);
  _impl_.psns_.InternalSwap(&other->_impl_.psns_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RdmaSessionResponse, _impl_.rkey_)
      + sizeof(RdmaSessionResponse::_impl_.rkey_)
      - PROTOBUF_FIELD_OFFSET(RdmaSessionResponse, _impl_.session_id_)>(
          reinterpret_cast<char*>(&_impl_.session_id_),
          reinterpret_cast<char*>(&other->_impl_.session_id_));
}

::google::protobuf::Metadata RdmaSessionResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class BarrierRequest::_Internal {
 public:
};

BarrierRequest::BarrierRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:flashreduce_proto.BarrierRequest)
}
BarrierRequest::BarrierRequest(
    ::google::protobuf::Arena* arena, const BarrierRequest& from)
    : BarrierRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE BarrierRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void BarrierRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.num_workers_ = {};
}
BarrierRequest::~BarrierRequest() {
  // @@protoc_insertion_point(destructor:flashreduce_proto.BarrierRequest)
  SharedDtor(*this);
}
inline void BarrierRequest::SharedDtor(MessageLite& self) {
  BarrierRequest& this_ = static_cast<BarrierRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* BarrierRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) BarrierRequest(arena);
}
constexpr auto BarrierRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(BarrierRequest),
                                            alignof(BarrierRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull BarrierRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_BarrierRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &BarrierRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<BarrierRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &BarrierRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<BarrierRequest>(), &BarrierRequest::ByteSizeLong,
            &BarrierRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(BarrierRequest, _impl_._cached_size_),
        false,
    },
    &BarrierRequest::kDescriptorMethods,
    &descriptor_table_flashreduce_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* BarrierRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> BarrierRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::flashreduce_proto::BarrierRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 num_workers = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BarrierRequest, _impl_.num_workers_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(BarrierRequest, _impl_.num_workers_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 num_workers = 1;
    {PROTOBUF_FIELD_OFFSET(BarrierRequest, _impl_.num_workers_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void BarrierRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:flashreduce_proto.BarrierRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.num_workers_ = 0u;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* BarrierRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const BarrierRequest& this_ = static_cast<const BarrierRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* BarrierRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const BarrierRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:flashreduce_proto.BarrierRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 num_workers = 1;
          if (this_._internal_num_workers() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_num_workers(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:flashreduce_proto.BarrierRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t BarrierRequest::ByteSizeLong(const MessageLite& base) {
          const BarrierRequest& this_ = static_cast<const BarrierRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t BarrierRequest::ByteSizeLong() const {
          const BarrierRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:flashreduce_proto.BarrierRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // uint32 num_workers = 1;
            if (this_._internal_num_workers() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_num_workers());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void BarrierRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<BarrierRequest*>(&to_msg);
  auto& from = static_cast<const BarrierRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:flashreduce_proto.BarrierRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_num_workers() != 0) {
    _this->_impl_.num_workers_ = from._impl_.num_workers_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BarrierRequest::CopyFrom(const BarrierRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:flashreduce_proto.BarrierRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BarrierRequest::InternalSwap(BarrierRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.num_workers_, other->_impl_.num_workers_);
}

::google::protobuf::Metadata BarrierRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class BarrierResponse::_Internal {
 public:
};

BarrierResponse::BarrierResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:flashreduce_proto.BarrierResponse)
}
BarrierResponse::BarrierResponse(
    ::google::protobuf::Arena* arena,
    const BarrierResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BarrierResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:flashreduce_proto.BarrierResponse)
}

inline void* BarrierResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) BarrierResponse(arena);
}
constexpr auto BarrierResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(BarrierResponse),
                                            alignof(BarrierResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull BarrierResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_BarrierResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &BarrierResponse::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<BarrierResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &BarrierResponse::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<BarrierResponse>(), &BarrierResponse::ByteSizeLong,
            &BarrierResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(BarrierResponse, _impl_._cached_size_),
        false,
    },
    &BarrierResponse::kDescriptorMethods,
    &descriptor_table_flashreduce_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* BarrierResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> BarrierResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::flashreduce_proto::BarrierResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata BarrierResponse::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class BroadcastRequest::_Internal {
 public:
};

BroadcastRequest::BroadcastRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:flashreduce_proto.BroadcastRequest)
}
BroadcastRequest::BroadcastRequest(
    ::google::protobuf::Arena* arena, const BroadcastRequest& from)
    : BroadcastRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE BroadcastRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void BroadcastRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, value_),
           0,
           offsetof(Impl_, root_) -
               offsetof(Impl_, value_) +
               sizeof(Impl_::root_));
}
BroadcastRequest::~BroadcastRequest() {
  // @@protoc_insertion_point(destructor:flashreduce_proto.BroadcastRequest)
  SharedDtor(*this);
}
inline void BroadcastRequest::SharedDtor(MessageLite& self) {
  BroadcastRequest& this_ = static_cast<BroadcastRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* BroadcastRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) BroadcastRequest(arena);
}
constexpr auto BroadcastRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(BroadcastRequest),
                                            alignof(BroadcastRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull BroadcastRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_BroadcastRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &BroadcastRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<BroadcastRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &BroadcastRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<BroadcastRequest>(), &BroadcastRequest::ByteSizeLong,
            &BroadcastRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(BroadcastRequest, _impl_._cached_size_),
        false,
    },
    &BroadcastRequest::kDescriptorMethods,
    &descriptor_table_flashreduce_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* BroadcastRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2> BroadcastRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::flashreduce_proto::BroadcastRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 root = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BroadcastRequest, _impl_.root_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(BroadcastRequest, _impl_.root_)}},
    // uint64 value = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(BroadcastRequest, _impl_.value_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(BroadcastRequest, _impl_.value_)}},
    // uint32 rank = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BroadcastRequest, _impl_.rank_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(BroadcastRequest, _impl_.rank_)}},
    // uint32 num_workers = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BroadcastRequest, _impl_.num_workers_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(BroadcastRequest, _impl_.num_workers_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 value = 1;
    {PROTOBUF_FIELD_OFFSET(BroadcastRequest, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint32 rank = 2;
    {PROTOBUF_FIELD_OFFSET(BroadcastRequest, _impl_.rank_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 num_workers = 3;
    {PROTOBUF_FIELD_OFFSET(BroadcastRequest, _impl_.num_workers_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 root = 4;
    {PROTOBUF_FIELD_OFFSET(BroadcastRequest, _impl_.root_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void BroadcastRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:flashreduce_proto.BroadcastRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.value_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.root_) -
      reinterpret_cast<char*>(&_impl_.value_)) + sizeof(_impl_.root_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* BroadcastRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const BroadcastRequest& this_ = static_cast<const BroadcastRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* BroadcastRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const BroadcastRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:flashreduce_proto.BroadcastRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 value = 1;
          if (this_._internal_value() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_value(), target);
          }

          // uint32 rank = 2;
          if (this_._internal_rank() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_rank(), target);
          }

          // uint32 num_workers = 3;
          if (this_._internal_num_workers() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                3, this_._internal_num_workers(), target);
          }

          // uint32 root = 4;
          if (this_._internal_root() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                4, this_._internal_root(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:flashreduce_proto.BroadcastRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t BroadcastRequest::ByteSizeLong(const MessageLite& base) {
          const BroadcastRequest& this_ = static_cast<const BroadcastRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t BroadcastRequest::ByteSizeLong() const {
          const BroadcastRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:flashreduce_proto.BroadcastRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // uint64 value = 1;
            if (this_._internal_value() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_value());
            }
            // uint32 rank = 2;
            if (this_._internal_rank() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_rank());
            }
            // uint32 num_workers = 3;
            if (this_._internal_num_workers() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_num_workers());
            }
            // uint32 root = 4;
            if (this_._internal_root() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_root());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void BroadcastRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<BroadcastRequest*>(&to_msg);
  auto& from = static_cast<const BroadcastRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:flashreduce_proto.BroadcastRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_value() != 0) {
    _this->_impl_.value_ = from._impl_.value_;
  }
  if (from._internal_rank() != 0) {
    _this->_impl_.rank_ = from._impl_.rank_;
  }
  if (from._internal_num_workers() != 0) {
    _this->_impl_.num_workers_ = from._impl_.num_workers_;
  }
  if (from._internal_root() != 0) {
    _this->_impl_.root_ = from._impl_.root_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BroadcastRequest::CopyFrom(const BroadcastRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:flashreduce_proto.BroadcastRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BroadcastRequest::InternalSwap(BroadcastRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BroadcastRequest, _impl_.root_)
      + sizeof(BroadcastRequest::_impl_.root_)
      - PROTOBUF_FIELD_OFFSET(BroadcastRequest, _impl_.value_)>(
          reinterpret_cast<char*>(&_impl_.value_),
          reinterpret_cast<char*>(&other->_impl_.value_));
}

::google::protobuf::Metadata BroadcastRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class BroadcastResponse::_Internal {
 public:
};

BroadcastResponse::BroadcastResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:flashreduce_proto.BroadcastResponse)
}
BroadcastResponse::BroadcastResponse(
    ::google::protobuf::Arena* arena, const BroadcastResponse& from)
    : BroadcastResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE BroadcastResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void BroadcastResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.value_ = {};
}
BroadcastResponse::~BroadcastResponse() {
  // @@protoc_insertion_point(destructor:flashreduce_proto.BroadcastResponse)
  SharedDtor(*this);
}
inline void BroadcastResponse::SharedDtor(MessageLite& self) {
  BroadcastResponse& this_ = static_cast<BroadcastResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* BroadcastResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) BroadcastResponse(arena);
}
constexpr auto BroadcastResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(BroadcastResponse),
                                            alignof(BroadcastResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull BroadcastResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_BroadcastResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &BroadcastResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<BroadcastResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &BroadcastResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<BroadcastResponse>(), &BroadcastResponse::ByteSizeLong,
            &BroadcastResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(BroadcastResponse, _impl_._cached_size_),
        false,
    },
    &BroadcastResponse::kDescriptorMethods,
    &descriptor_table_flashreduce_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* BroadcastResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> BroadcastResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::flashreduce_proto::BroadcastResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 value = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(BroadcastResponse, _impl_.value_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(BroadcastResponse, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 value = 1;
    {PROTOBUF_FIELD_OFFSET(BroadcastResponse, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void BroadcastResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:flashreduce_proto.BroadcastResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_ = ::uint64_t{0u};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* BroadcastResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const BroadcastResponse& this_ = static_cast<const BroadcastResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* BroadcastResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const BroadcastResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:flashreduce_proto.BroadcastResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 value = 1;
          if (this_._internal_value() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_value(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:flashreduce_proto.BroadcastResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t BroadcastResponse::ByteSizeLong(const MessageLite& base) {
          const BroadcastResponse& this_ = static_cast<const BroadcastResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t BroadcastResponse::ByteSizeLong() const {
          const BroadcastResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:flashreduce_proto.BroadcastResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // uint64 value = 1;
            if (this_._internal_value() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_value());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void BroadcastResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<BroadcastResponse*>(&to_msg);
  auto& from = static_cast<const BroadcastResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:flashreduce_proto.BroadcastResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_value() != 0) {
    _this->_impl_.value_ = from._impl_.value_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BroadcastResponse::CopyFrom(const BroadcastResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:flashreduce_proto.BroadcastResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BroadcastResponse::InternalSwap(BroadcastResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.value_, other->_impl_.value_);
}

::google::protobuf::Metadata BroadcastResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace flashreduce_proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_flashreduce_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
